// Generated by `hot-updater db generate` from Hot Updater's schema. Do not edit.
import { customType, index, primaryKey, sqliteTable, uniqueIndex } from "drizzle-orm/sqlite-core";

/** A column typed exactly as Hot Updater's SQL schema declares it. */
const column = (type: string) =>
  customType<{ data: unknown; driverData: unknown }>({ dataType: () => type });

export const bundles = sqliteTable("bundles", {
  "id": column("TEXT")("id").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "git_commit_hash": column("TEXT")("git_commit_hash"),
  "metadata": column("TEXT")("metadata").notNull(),
  "manifest_storage_uri": column("TEXT")("manifest_storage_uri").notNull(),
  "manifest_file_hash": column("TEXT")("manifest_file_hash").notNull(),
  "asset_base_storage_uri": column("TEXT")("asset_base_storage_uri").notNull(),
  "_refs_bundle_patches_bundle_id": column("INTEGER")("_refs_bundle_patches_bundle_id").notNull().default(0),
  "_refs_bundle_patches_base_bundle_id": column("INTEGER")("_refs_bundle_patches_base_bundle_id").notNull().default(0),
  "_refs_releases_bundle_id": column("INTEGER")("_refs_releases_bundle_id").notNull().default(0),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("bundles_byPlatform").on(table["platform"], table["id"]),
]);

export const channels = sqliteTable("channels", {
  "id": column("TEXT")("id").notNull(),
  "name": column("TEXT")("name").notNull(),
  "_refs_releases_channel_id": column("INTEGER")("_refs_releases_channel_id").notNull().default(0),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("channels_all").on(table["name"], table["id"]),
  uniqueIndex("channels_name").on(table["name"]),
]);

export const bundle_totals = sqliteTable("bundle_totals", {
  "platform_key": column("TEXT")("platform_key").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "bundles": column("INTEGER")("bundles").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform_key"], table["_shard"]] }),
]);

export const base_candidates = sqliteTable("base_candidates", {
  "candidate_key": column("TEXT")("candidate_key").notNull(),
  "bundle_id": column("TEXT")("bundle_id").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "releases": column("INTEGER")("releases").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["candidate_key"], table["bundle_id"], table["_shard"]] }),
]);

export const bundle_events = sqliteTable("bundle_events", {
  "id": column("TEXT")("id").notNull(),
  "type": column("TEXT")("type").notNull(),
  "install_id": column("TEXT")("install_id").notNull(),
  "user_id": column("TEXT")("user_id"),
  "from_release_id": column("TEXT")("from_release_id"),
  "from_bundle_id": column("TEXT")("from_bundle_id"),
  "to_release_id": column("TEXT")("to_release_id"),
  "to_bundle_id": column("TEXT")("to_bundle_id").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "app_version": column("TEXT")("app_version").notNull(),
  "channel": column("TEXT")("channel").notNull(),
  "metadata": column("TEXT")("metadata").notNull(),
  "received_at_ms": column("INTEGER")("received_at_ms").notNull(),
  "day": column("INTEGER")("day"),
  "movement_install_id": column("TEXT")("movement_install_id"),
  "bundle_ref": column("TEXT")("bundle_ref"),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("bundle_events_recent").on(table["channel"], table["platform"], table["day"], table["received_at_ms"], table["id"]),
  index("bundle_events_movementsByInstall").on(table["movement_install_id"], table["received_at_ms"], table["id"]),
  index("bundle_events_byDay").on(table["day"], table["received_at_ms"], table["id"]),
]);

export const bundle_events__byBundle = sqliteTable("bundle_events__byBundle", {
  "platform": column("TEXT")("platform").notNull(),
  "channel": column("TEXT")("channel").notNull(),
  "type": column("TEXT")("type").notNull(),
  "bundle_ref": column("TEXT")("bundle_ref").notNull(),
  "day": column("INTEGER")("day").notNull(),
  "received_at_ms": column("INTEGER")("received_at_ms").notNull(),
  "id": column("TEXT")("id").notNull(),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["type"], table["bundle_ref"], table["day"], table["received_at_ms"], table["id"]] }),
]);

export const bundle_event_heads = sqliteTable("bundle_event_heads", {
  "install_id": column("TEXT")("install_id").notNull(),
  "id": column("TEXT")("id").notNull(),
  "type": column("TEXT")("type").notNull(),
  "user_id": column("TEXT")("user_id"),
  "from_release_id": column("TEXT")("from_release_id"),
  "from_bundle_id": column("TEXT")("from_bundle_id"),
  "to_release_id": column("TEXT")("to_release_id"),
  "to_bundle_id": column("TEXT")("to_bundle_id").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "app_version": column("TEXT")("app_version").notNull(),
  "channel": column("TEXT")("channel").notNull(),
  "metadata": column("TEXT")("metadata").notNull(),
  "received_at_ms": column("INTEGER")("received_at_ms").notNull(),
  "current_release_id": column("TEXT")("current_release_id"),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["install_id"]] }),
  index("bundle_event_heads_byUser").on(table["user_id"], table["install_id"]),
]);

export const insights_overview = sqliteTable("insights_overview", {
  "identity": column("TEXT")("identity").notNull(),
  "bucket_start_ms": column("INTEGER")("bucket_start_ms").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "downloads": column("INTEGER")("downloads").notNull(),
  "launches": column("INTEGER")("launches").notNull(),
  "failed_launches": column("INTEGER")("failed_launches").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["identity"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_sketches = sqliteTable("insights_sketches", {
  "identity": column("TEXT")("identity").notNull(),
  "bucket_start_ms": column("INTEGER")("bucket_start_ms").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "launch_users": column("TEXT")("launch_users"),
  "activity_users": column("TEXT")("activity_users"),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["identity"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_distribution = sqliteTable("insights_distribution", {
  "channel": column("TEXT")("channel").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "app_version": column("TEXT")("app_version").notNull(),
  "release_id": column("TEXT")("release_id").notNull(),
  "bucket_start_ms": column("INTEGER")("bucket_start_ms").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "latest_installations": column("INTEGER")("latest_installations").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["channel"], table["platform"], table["app_version"], table["release_id"], table["bucket_start_ms"], table["_shard"]] }),
  index("insights_distribution_byScope").on(table["channel"], table["platform"], table["bucket_start_ms"], table["app_version"], table["release_id"], table["_shard"]),
  index("insights_distribution_byVersion").on(table["channel"], table["platform"], table["app_version"], table["bucket_start_ms"], table["release_id"], table["_shard"]),
]);

export const insights_latest_by_bundle = sqliteTable("insights_latest_by_bundle", {
  "platform": column("TEXT")("platform").notNull(),
  "channel": column("TEXT")("channel").notNull(),
  "bundle_field": column("TEXT")("bundle_field").notNull(),
  "bundle_id": column("TEXT")("bundle_id").notNull(),
  "type": column("TEXT")("type").notNull(),
  "bucket_start_ms": column("INTEGER")("bucket_start_ms").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "installations": column("INTEGER")("installations").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["bundle_field"], table["bundle_id"], table["type"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_outcomes = sqliteTable("insights_outcomes", {
  "platform": column("TEXT")("platform").notNull(),
  "channel": column("TEXT")("channel").notNull(),
  "type": column("TEXT")("type").notNull(),
  "bundle_ref": column("TEXT")("bundle_ref").notNull(),
  "bucket_start_ms": column("INTEGER")("bucket_start_ms").notNull(),
  "_shard": column("INTEGER")("_shard").notNull(),
  "events": column("INTEGER")("events").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["type"], table["bundle_ref"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const api_keys = sqliteTable("api_keys", {
  "id": column("TEXT")("id").notNull(),
  "hash": column("TEXT")("hash").notNull(),
  "name": column("TEXT")("name").notNull(),
  "prefix": column("TEXT")("prefix").notNull(),
  "role": column("TEXT")("role").notNull(),
  "created_at_ms": column("INTEGER")("created_at_ms").notNull(),
  "revoked_at_ms": column("INTEGER")("revoked_at_ms"),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("api_keys_byCreated").on(table["created_at_ms"], table["id"]),
  uniqueIndex("api_keys_hash").on(table["hash"]),
]);

export const bundle_patches = sqliteTable("bundle_patches", {
  "id": column("TEXT")("id").notNull(),
  "bundle_id": column("TEXT")("bundle_id").notNull(),
  "base_bundle_id": column("TEXT")("base_bundle_id").notNull(),
  "base_file_hash": column("TEXT")("base_file_hash").notNull(),
  "patch_file_hash": column("TEXT")("patch_file_hash").notNull(),
  "patch_storage_uri": column("TEXT")("patch_storage_uri").notNull(),
  "byte_size": column("INTEGER")("byte_size").notNull(),
  "order_index": column("INTEGER")("order_index").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  uniqueIndex("bundle_patches_pair").on(table["bundle_id"], table["base_bundle_id"]),
  index("bundle_patches_byBundle").on(table["bundle_id"], table["order_index"], table["id"]),
  index("bundle_patches_byBase").on(table["base_bundle_id"], table["bundle_id"], table["id"]),
]);

export const releases = sqliteTable("releases", {
  "id": column("TEXT")("id").notNull(),
  "revision": column("INTEGER")("revision").notNull(),
  "scope_key": column("TEXT")("scope_key").notNull(),
  "channel_id": column("TEXT")("channel_id").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "kind": column("TEXT")("kind").notNull(),
  "bundle_id": column("TEXT")("bundle_id"),
  "strategy": column("TEXT")("strategy").notNull(),
  "target_app_version": column("TEXT")("target_app_version"),
  "fingerprint_hash": column("TEXT")("fingerprint_hash"),
  "enabled": column("INTEGER")("enabled").notNull(),
  "should_force_update": column("INTEGER")("should_force_update").notNull(),
  "message": column("TEXT")("message"),
  "rollout_cohort_count": column("INTEGER")("rollout_cohort_count").notNull(),
  "target_cohorts": column("TEXT")("target_cohorts").notNull(),
  "operation": column("TEXT")("operation").notNull(),
  "source_release_id": column("TEXT")("source_release_id"),
  "created_at_ms": column("INTEGER")("created_at_ms").notNull(),
  "updated_at_ms": column("INTEGER")("updated_at_ms").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("releases_byScope").on(table["scope_key"], table["id"]),
  index("releases_byScopeEnabled").on(table["scope_key"], table["enabled"], table["id"]),
  index("releases_byChannelPlatform").on(table["channel_id"], table["platform"], table["id"]),
  index("releases_byChannelPlatformEnabled").on(table["channel_id"], table["platform"], table["enabled"], table["id"]),
  index("releases_byBundle").on(table["bundle_id"], table["id"]),
]);

export const release_catalogs = sqliteTable("release_catalogs", {
  "scope_key": column("TEXT")("scope_key").notNull(),
  "catalog_id": column("TEXT")("catalog_id").notNull(),
  "strategy": column("TEXT")("strategy").notNull(),
  "channel_id": column("TEXT")("channel_id").notNull(),
  "channel_key": column("TEXT")("channel_key").notNull(),
  "platform": column("TEXT")("platform").notNull(),
  "fingerprint_hash": column("TEXT")("fingerprint_hash"),
  "generation": column("INTEGER")("generation").notNull(),
  "payload": column("TEXT")("payload").notNull(),
  "catalog_hash": column("TEXT")("catalog_hash").notNull(),
  "byte_size": column("INTEGER")("byte_size").notNull(),
  "is_tombstone": column("INTEGER")("is_tombstone").notNull(),
  "updated_at_ms": column("INTEGER")("updated_at_ms").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["scope_key"]] }),
]);

export const private_hot_updater_settings = sqliteTable("private_hot_updater_settings", {
  "key": column("TEXT")("key").notNull(),
  "value": column("TEXT")("value").notNull(),
  "_v": column("INTEGER")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["key"]] }),
]);
