// Generated by `hot-updater db generate` from Hot Updater's schema. Do not edit.
import { customType, foreignKey, index, pgTable, primaryKey, uniqueIndex } from "drizzle-orm/pg-core";

/** A column typed exactly as Hot Updater's SQL schema declares it. */
const column = (type: string) =>
  customType<{ data: unknown; driverData: unknown }>({ dataType: () => type });

export const bundles = pgTable("bundles", {
  "id": column("varchar(36) COLLATE \"C\"")("id").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "git_commit_hash": column("varchar(255) COLLATE \"C\"")("git_commit_hash"),
  "metadata": column("jsonb")("metadata").notNull(),
  "manifest_storage_uri": column("text COLLATE \"C\"")("manifest_storage_uri").notNull(),
  "manifest_file_hash": column("text COLLATE \"C\"")("manifest_file_hash").notNull(),
  "asset_base_storage_uri": column("text COLLATE \"C\"")("asset_base_storage_uri").notNull(),
  "_refs_bundle_patches_bundle_id": column("bigint")("_refs_bundle_patches_bundle_id").notNull().default(0),
  "_refs_bundle_patches_base_bundle_id": column("bigint")("_refs_bundle_patches_base_bundle_id").notNull().default(0),
  "_refs_releases_bundle_id": column("bigint")("_refs_releases_bundle_id").notNull().default(0),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("bundles_byPlatform").on(table["platform"], table["id"]),
]);

export const channels = pgTable("channels", {
  "id": column("varchar(255) COLLATE \"C\"")("id").notNull(),
  "name": column("varchar(255) COLLATE \"C\"")("name").notNull(),
  "_refs_releases_channel_id": column("bigint")("_refs_releases_channel_id").notNull().default(0),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("channels_all").on(table["name"], table["id"]),
  uniqueIndex("channels_name").on(table["name"]),
]);

export const bundle_totals = pgTable("bundle_totals", {
  "platform_key": column("varchar(16) COLLATE \"C\"")("platform_key").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "bundles": column("bigint")("bundles").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform_key"], table["_shard"]] }),
]);

export const base_candidates = pgTable("base_candidates", {
  "candidate_key": column("varchar(2048) COLLATE \"C\"")("candidate_key").notNull(),
  "bundle_id": column("varchar(36) COLLATE \"C\"")("bundle_id").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "releases": column("bigint")("releases").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["candidate_key"], table["bundle_id"], table["_shard"]] }),
]);

export const bundle_events = pgTable("bundle_events", {
  "id": column("varchar(36) COLLATE \"C\"")("id").notNull(),
  "type": column("varchar(32) COLLATE \"C\"")("type").notNull(),
  "install_id": column("varchar(255) COLLATE \"C\"")("install_id").notNull(),
  "user_id": column("varchar(255) COLLATE \"C\"")("user_id"),
  "from_release_id": column("varchar(36) COLLATE \"C\"")("from_release_id"),
  "from_bundle_id": column("varchar(36) COLLATE \"C\"")("from_bundle_id"),
  "to_release_id": column("varchar(36) COLLATE \"C\"")("to_release_id"),
  "to_bundle_id": column("varchar(36) COLLATE \"C\"")("to_bundle_id").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "app_version": column("text COLLATE \"C\"")("app_version").notNull(),
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "metadata": column("jsonb")("metadata").notNull(),
  "received_at_ms": column("bigint")("received_at_ms").notNull(),
  "day": column("bigint")("day"),
  "movement_install_id": column("text COLLATE \"C\"")("movement_install_id"),
  "bundle_ref": column("jsonb")("bundle_ref"),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("bundle_events_recent").on(table["channel"], table["platform"], table["day"], table["received_at_ms"], table["id"]),
  index("bundle_events_movementsByInstall").on(table["movement_install_id"], table["received_at_ms"], table["id"]),
  index("bundle_events_byDay").on(table["day"], table["received_at_ms"], table["id"]),
]);

export const bundle_events__byBundle = pgTable("bundle_events__byBundle", {
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "type": column("varchar(32) COLLATE \"C\"")("type").notNull(),
  "bundle_ref": column("text COLLATE \"C\"")("bundle_ref").notNull(),
  "day": column("bigint")("day").notNull(),
  "received_at_ms": column("bigint")("received_at_ms").notNull(),
  "id": column("varchar(36) COLLATE \"C\"")("id").notNull(),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["type"], table["bundle_ref"], table["day"], table["received_at_ms"], table["id"]] }),
]);

export const bundle_event_heads = pgTable("bundle_event_heads", {
  "install_id": column("varchar(255) COLLATE \"C\"")("install_id").notNull(),
  "id": column("varchar(36) COLLATE \"C\"")("id").notNull(),
  "type": column("varchar(32) COLLATE \"C\"")("type").notNull(),
  "user_id": column("varchar(255) COLLATE \"C\"")("user_id"),
  "from_release_id": column("varchar(36) COLLATE \"C\"")("from_release_id"),
  "from_bundle_id": column("varchar(36) COLLATE \"C\"")("from_bundle_id"),
  "to_release_id": column("varchar(36) COLLATE \"C\"")("to_release_id"),
  "to_bundle_id": column("varchar(36) COLLATE \"C\"")("to_bundle_id").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "app_version": column("text COLLATE \"C\"")("app_version").notNull(),
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "metadata": column("jsonb")("metadata").notNull(),
  "received_at_ms": column("bigint")("received_at_ms").notNull(),
  "current_release_id": column("varchar(36) COLLATE \"C\"")("current_release_id"),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["install_id"]] }),
  index("bundle_event_heads_byUser").on(table["user_id"], table["install_id"]),
]);

export const insights_overview = pgTable("insights_overview", {
  "identity": column("varchar(32) COLLATE \"C\"")("identity").notNull(),
  "bucket_start_ms": column("bigint")("bucket_start_ms").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "downloads": column("bigint")("downloads").notNull(),
  "launches": column("bigint")("launches").notNull(),
  "failed_launches": column("bigint")("failed_launches").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["identity"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_sketches = pgTable("insights_sketches", {
  "identity": column("varchar(32) COLLATE \"C\"")("identity").notNull(),
  "bucket_start_ms": column("bigint")("bucket_start_ms").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "launch_users": column("text COLLATE \"C\"")("launch_users"),
  "activity_users": column("text COLLATE \"C\"")("activity_users"),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["identity"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_distribution = pgTable("insights_distribution", {
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "app_version": column("text COLLATE \"C\"")("app_version").notNull(),
  "release_id": column("varchar(36) COLLATE \"C\"")("release_id").notNull(),
  "bucket_start_ms": column("bigint")("bucket_start_ms").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "latest_installations": column("bigint")("latest_installations").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["channel"], table["platform"], table["app_version"], table["release_id"], table["bucket_start_ms"], table["_shard"]] }),
  index("insights_distribution_byScope").on(table["channel"], table["platform"], table["bucket_start_ms"], table["app_version"], table["release_id"], table["_shard"]),
  index("insights_distribution_byVersion").on(table["channel"], table["platform"], table["app_version"], table["bucket_start_ms"], table["release_id"], table["_shard"]),
]);

export const insights_latest_by_bundle = pgTable("insights_latest_by_bundle", {
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "bundle_field": column("varchar(16) COLLATE \"C\"")("bundle_field").notNull(),
  "bundle_id": column("varchar(36) COLLATE \"C\"")("bundle_id").notNull(),
  "type": column("varchar(32) COLLATE \"C\"")("type").notNull(),
  "bucket_start_ms": column("bigint")("bucket_start_ms").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "installations": column("bigint")("installations").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["bundle_field"], table["bundle_id"], table["type"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const insights_outcomes = pgTable("insights_outcomes", {
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "channel": column("text COLLATE \"C\"")("channel").notNull(),
  "type": column("varchar(32) COLLATE \"C\"")("type").notNull(),
  "bundle_ref": column("varchar(41) COLLATE \"C\"")("bundle_ref").notNull(),
  "bucket_start_ms": column("bigint")("bucket_start_ms").notNull(),
  "_shard": column("bigint")("_shard").notNull(),
  "events": column("bigint")("events").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["platform"], table["channel"], table["type"], table["bundle_ref"], table["bucket_start_ms"], table["_shard"]] }),
]);

export const api_keys = pgTable("api_keys", {
  "id": column("varchar(255) COLLATE \"C\"")("id").notNull(),
  "hash": column("varchar(64) COLLATE \"C\"")("hash").notNull(),
  "name": column("varchar(64) COLLATE \"C\"")("name").notNull(),
  "prefix": column("varchar(16) COLLATE \"C\"")("prefix").notNull(),
  "role": column("varchar(16) COLLATE \"C\"")("role").notNull(),
  "created_at_ms": column("bigint")("created_at_ms").notNull(),
  "revoked_at_ms": column("bigint")("revoked_at_ms"),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("api_keys_byCreated").on(table["created_at_ms"], table["id"]),
  uniqueIndex("api_keys_hash").on(table["hash"]),
]);

export const bundle_patches = pgTable("bundle_patches", {
  "id": column("varchar(255) COLLATE \"C\"")("id").notNull(),
  "bundle_id": column("varchar(36) COLLATE \"C\"")("bundle_id").notNull(),
  "base_bundle_id": column("varchar(36) COLLATE \"C\"")("base_bundle_id").notNull(),
  "base_file_hash": column("text COLLATE \"C\"")("base_file_hash").notNull(),
  "patch_file_hash": column("text COLLATE \"C\"")("patch_file_hash").notNull(),
  "patch_storage_uri": column("text COLLATE \"C\"")("patch_storage_uri").notNull(),
  "byte_size": column("bigint")("byte_size").notNull(),
  "order_index": column("bigint")("order_index").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  uniqueIndex("bundle_patches_pair").on(table["bundle_id"], table["base_bundle_id"]),
  index("bundle_patches_byBundle").on(table["bundle_id"], table["order_index"], table["id"]),
  index("bundle_patches_byBase").on(table["base_bundle_id"], table["bundle_id"], table["id"]),
  foreignKey({ name: "bundle_patches_bundle_id_fk", columns: [table["bundle_id"]], foreignColumns: [bundles["id"]] }).onDelete("cascade"),
  foreignKey({ name: "bundle_patches_base_bundle_id_fk", columns: [table["base_bundle_id"]], foreignColumns: [bundles["id"]] }).onDelete("cascade"),
]);

export const releases = pgTable("releases", {
  "id": column("varchar(36) COLLATE \"C\"")("id").notNull(),
  "revision": column("bigint")("revision").notNull(),
  "scope_key": column("varchar(2048) COLLATE \"C\"")("scope_key").notNull(),
  "channel_id": column("varchar(255) COLLATE \"C\"")("channel_id").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "kind": column("varchar(16) COLLATE \"C\"")("kind").notNull(),
  "bundle_id": column("varchar(36) COLLATE \"C\"")("bundle_id"),
  "strategy": column("varchar(16) COLLATE \"C\"")("strategy").notNull(),
  "target_app_version": column("text COLLATE \"C\"")("target_app_version"),
  "fingerprint_hash": column("varchar(255) COLLATE \"C\"")("fingerprint_hash"),
  "enabled": column("boolean")("enabled").notNull(),
  "should_force_update": column("boolean")("should_force_update").notNull(),
  "message": column("text COLLATE \"C\"")("message"),
  "rollout_cohort_count": column("bigint")("rollout_cohort_count").notNull(),
  "target_cohorts": column("jsonb")("target_cohorts").notNull(),
  "operation": column("varchar(16) COLLATE \"C\"")("operation").notNull(),
  "source_release_id": column("varchar(36) COLLATE \"C\"")("source_release_id"),
  "created_at_ms": column("bigint")("created_at_ms").notNull(),
  "updated_at_ms": column("bigint")("updated_at_ms").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["id"]] }),
  index("releases_byScope").on(table["scope_key"], table["id"]),
  index("releases_byScopeEnabled").on(table["scope_key"], table["enabled"], table["id"]),
  index("releases_byChannelPlatform").on(table["channel_id"], table["platform"], table["id"]),
  index("releases_byChannelPlatformEnabled").on(table["channel_id"], table["platform"], table["enabled"], table["id"]),
  index("releases_byBundle").on(table["bundle_id"], table["id"]),
  foreignKey({ name: "releases_channel_id_fk", columns: [table["channel_id"]], foreignColumns: [channels["id"]] }).onDelete("restrict"),
  foreignKey({ name: "releases_bundle_id_fk", columns: [table["bundle_id"]], foreignColumns: [bundles["id"]] }).onDelete("restrict"),
]);

export const release_catalogs = pgTable("release_catalogs", {
  "scope_key": column("varchar(2048) COLLATE \"C\"")("scope_key").notNull(),
  "catalog_id": column("varchar(255) COLLATE \"C\"")("catalog_id").notNull(),
  "strategy": column("varchar(16) COLLATE \"C\"")("strategy").notNull(),
  "channel_id": column("varchar(255) COLLATE \"C\"")("channel_id").notNull(),
  "channel_key": column("varchar(1400) COLLATE \"C\"")("channel_key").notNull(),
  "platform": column("varchar(16) COLLATE \"C\"")("platform").notNull(),
  "fingerprint_hash": column("varchar(255) COLLATE \"C\"")("fingerprint_hash"),
  "generation": column("bigint")("generation").notNull(),
  "payload": column("text COLLATE \"C\"")("payload").notNull(),
  "catalog_hash": column("varchar(71) COLLATE \"C\"")("catalog_hash").notNull(),
  "byte_size": column("bigint")("byte_size").notNull(),
  "is_tombstone": column("boolean")("is_tombstone").notNull(),
  "updated_at_ms": column("bigint")("updated_at_ms").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["scope_key"]] }),
]);

export const private_hot_updater_settings = pgTable("private_hot_updater_settings", {
  "key": column("varchar(255) COLLATE \"C\"")("key").notNull(),
  "value": column("varchar(255) COLLATE \"C\"")("value").notNull(),
  "_v": column("bigint")("_v").notNull().default(0),
}, (table) => [
  primaryKey({ columns: [table["key"]] }),
]);
