packages:
  - packages/*
  - plugins/*
  - docs
  - docs2
  - examples/*
  - examples-server/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - typia
  - workerd

catalog:
  "@clack/prompts": 0.10.0
  "@types/node": ^20
  "execa": 9.5.2
  "picocolors": 1.1.1
