packages:
  - packages/*
  - plugins/*
  - docs
  - examples/*
  - examples-server/*

catalog:
  '@types/node': ^20
  execa: 9.5.2

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - typia
  - workerd

patchedDependencies:
  fumadocs-core: patches/fumadocs-core.patch
