packages:
  - packages/*
  - plugins/*
  - docs
  - examples/*
  - examples-server/*

catalog:
  '@types/node': ^20
  vitest: 4.1.0
catalogs:
  tools:
   tsdown: 0.21.6
   '@clack/prompts': 1.0.1
   'execa': 9.5.2
  hono:
    hono: 4.12.9
    '@hono/node-server': 1.19.11
  
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@biomejs/biome'
  - '@firebase/util'
  - '@sentry/cli'
  - '@swc/core'
  - aws-sdk
  - better-sqlite3
  - core-js
  - core-js-pure
  - cpu-features
  - esbuild
  - msw
  - nx
  - prisma
  - protobufjs
  - re2
  - sharp
  - ssh2
  - typia
  - workerd
