packages:
  - packages/*
  - plugins/*
  - docs
  - examples/*
  - examples-server/*

catalog:
  '@types/node': ^20
  execa: 9.5.2

ignoredBuiltDependencies:
  - '@firebase/util'
  - cpu-features
  - protobufjs
  - re2
  - ssh2

onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - '@swc/core'
  - aws-sdk
  - better-sqlite3
  - core-js-pure
  - esbuild
  - msw
  - nx
  - prisma
  - sharp
  - typia
  - workerd
