packages:
  - packages/*
  - plugins/*
  - docs
  - examples/*
  - examples-server/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - "@swc/core"
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - typia
  - workerd

catalog:
  "@types/node": ^20
  "execa": 9.5.2
