packages:
  - packages/*
  - plugins/*
  - docs
  - examples/*
onlyBuiltDependencies:
  - '@sentry/cli'
  - '@swc/core'
  - core-js-pure
  - esbuild
  - nx
  - sharp
  - typia
  - workerd
patchedDependencies:
  '@rnef/tools': patches/@rnef__tools.patch
