import { SETTINGS_TABLE } from "../database/fence";
import type { ResolvedSchema } from "../database/resolveSchema";
import {
  sqlTableShapes,
  type SqlDialect,
  type SqlTableShape,
} from "../database/sql/sqlSchema";

const drizzle = {
  postgresql: { module: "drizzle-orm/pg-core", table: "pgTable" },
  mysql: { module: "drizzle-orm/mysql-core", table: "mysqlTable" },
  sqlite: { module: "drizzle-orm/sqlite-core", table: "sqliteTable" },
} as const;

const literal = (value: string) => JSON.stringify(value);

/**
 * The Drizzle schema `drizzle-kit` applies for the engine's tables: every
 * column typed exactly as the engine's DDL, keys, indexes, index tables, and
 * the settings table. The engine keeps references itself, so there are no
 * foreign keys. `hot-updater db migrate` then writes only the settings rows.
 */
export const generateDrizzleEngineSchema = (
  dialect: SqlDialect,
  schema: ResolvedSchema,
): string => {
  const { module, table: tableFunction } = drizzle[dialect];
  const tables = [...schema.tables, SETTINGS_TABLE];
  const blocks: string[] = [];
  const emit = (shape: SqlTableShape) => {
    const columns = shape.columns.map(
      (column) =>
        `  ${literal(column.name)}: column(${literal(column.type)})(${literal(column.name)})${column.notNull ? ".notNull()" : ""}${column.default === undefined ? "" : `.default(${column.default})`},`,
    );
    const at = (name: string) => `table[${literal(name)}]`;
    const extras = [
      `primaryKey({ columns: [${shape.key.map(at).join(", ")}] })`,
      ...shape.indexes.flatMap((index) =>
        index.kind === "index"
          ? [
              `${index.unique ? "uniqueIndex" : "index"}(${literal(index.name)}).on(${index.columns.map(at).join(", ")})`,
            ]
          : [],
      ),
    ];
    blocks.push(
      `export const ${shape.name} = ${tableFunction}(${literal(shape.name)}, {\n${columns.join("\n")}\n}, (table) => [\n${extras.map((extra) => `  ${extra},`).join("\n")}\n]);`,
    );
    for (const index of shape.indexes) {
      if (index.kind === "table") emit(index.table);
    }
  };
  for (const shape of sqlTableShapes(dialect, tables)) emit(shape);
  const used = ["customType", "index", "primaryKey", "uniqueIndex"]
    .filter((name) =>
      name === "customType"
        ? true
        : blocks.some((block) => block.includes(`${name}(`)),
    )
    .concat(tableFunction)
    .sort();
  return [
    "// Generated by `hot-updater db generate` from Hot Updater's schema. Do not edit.",
    `import { ${used.join(", ")} } from ${literal(module)};`,
    "",
    "/** A column typed exactly as Hot Updater's SQL schema declares it. */",
    "const column = (type: string) =>",
    "  customType<{ data: unknown; driverData: unknown }>({ dataType: () => type });",
    "",
    ...blocks.flatMap((block) => [block, ""]),
  ].join("\n");
};
