import { SETTINGS_TABLE } from "../database/fence";
import type { ResolvedSchema } from "../database/resolveSchema";
import {
  sqlTableShapes,
  shortSqlName,
  type SqlDialect,
  type SqlTableShape,
} from "../database/sql/sqlSchema";

const drizzle = {
  postgresql: { module: "drizzle-orm/pg-core", table: "pgTable" },
  mysql: { module: "drizzle-orm/mysql-core", table: "mysqlTable" },
  sqlite: { module: "drizzle-orm/sqlite-core", table: "sqliteTable" },
} as const;

const literal = (value: string) => JSON.stringify(value);

/** Parents before children, so a foreign key names a table already declared. */
const byDepth = (schema: ResolvedSchema) => {
  const depths = new Map<string, number>();
  const depthOf = (name: string): number => {
    if (!depths.has(name)) {
      depths.set(name, 0);
      const parents = schema.models
        .get(name)!
        .references.filter(({ target }) => target !== name);
      depths.set(
        name,
        Math.max(0, ...parents.map(({ target }) => 1 + depthOf(target))),
      );
    }
    return depths.get(name)!;
  };
  return [...schema.tables].sort(
    (left, right) => depthOf(left.name) - depthOf(right.name),
  );
};

/**
 * The Drizzle schema `drizzle-kit` applies for the engine's tables: every
 * column typed exactly as the engine's DDL, keys, indexes, index tables, the
 * settings table, and foreign keys for `restrict` and `cascade` references
 * (until E2). `hot-updater db migrate` then writes only the settings rows.
 */
export const generateDrizzleEngineSchema = (
  dialect: SqlDialect,
  schema: ResolvedSchema,
  options: { readonly foreignKeys?: boolean } = {},
): string => {
  const { module, table: tableFunction } = drizzle[dialect];
  const tables = [...byDepth(schema), SETTINGS_TABLE];
  const blocks: string[] = [];
  const emit = (shape: SqlTableShape) => {
    const columns = shape.columns.map(
      (column) =>
        `  ${literal(column.name)}: column(${literal(column.type)})(${literal(column.name)})${column.notNull ? ".notNull()" : ""}${column.default === undefined ? "" : `.default(${column.default})`},`,
    );
    const at = (name: string) => `table[${literal(name)}]`;
    const extras = [
      `primaryKey({ columns: [${shape.key.map(at).join(", ")}] })`,
      ...shape.indexes.flatMap((index) =>
        index.kind === "index"
          ? [
              `${index.unique ? "uniqueIndex" : "index"}(${literal(index.name)}).on(${index.columns.map(at).join(", ")})`,
            ]
          : [],
      ),
      // SQLite gets none, as the shared SQL schema gives it none.
      ...(options.foreignKeys === false || dialect === "sqlite"
        ? []
        : (schema.models.get(shape.name)?.references ?? []).flatMap(
            ({ field, target, onDelete }) =>
              onDelete === "none"
                ? []
                : [
                    `foreignKey({ name: ${literal(shortSqlName(`${shape.name}_${field}_fk`))}, columns: [${at(field)}], foreignColumns: [${target}[${literal(schema.models.get(target)!.table.key[0]!)}]] }).onDelete(${literal(onDelete)})`,
                  ],
          )),
    ];
    blocks.push(
      `export const ${shape.name} = ${tableFunction}(${literal(shape.name)}, {\n${columns.join("\n")}\n}, (table) => [\n${extras.map((extra) => `  ${extra},`).join("\n")}\n]);`,
    );
    for (const index of shape.indexes) {
      if (index.kind === "table") emit(index.table);
    }
  };
  for (const shape of sqlTableShapes(dialect, tables)) emit(shape);
  const used = [
    "customType",
    "foreignKey",
    "index",
    "primaryKey",
    "uniqueIndex",
  ]
    .filter((name) =>
      name === "customType"
        ? true
        : blocks.some((block) => block.includes(`${name}(`)),
    )
    .concat(tableFunction)
    .sort();
  return [
    "// Generated by `hot-updater db generate` from Hot Updater's schema. Do not edit.",
    `import { ${used.join(", ")} } from ${literal(module)};`,
    "",
    "/** A column typed exactly as Hot Updater's SQL schema declares it. */",
    "const column = (type: string) =>",
    "  customType<{ data: unknown; driverData: unknown }>({ dataType: () => type });",
    "",
    ...blocks.flatMap((block) => [block, ""]),
  ].join("\n");
};
