import type { DetoxScenarioDefinition } from "./types.ts";

export const wave3Scenarios: readonly DetoxScenarioDefinition[] = [
  {
    name: "runtime-channel-switch-reset",
    wave: 3,
    steps: [
      { action: "launch", kind: "device", stage: "launch default channel" },
      {
        kind: "typeText",
        stage: "enter runtime channel",
        testID: "runtime-channel-input",
        text: "qa-runtime",
      },
      {
        kind: "tap",
        stage: "install runtime channel update",
        testID: "action-install-runtime-channel-update",
      },
      {
        contains: "runtime-channel:qa-runtime",
        kind: "assertText",
        stage: "assert runtime channel result",
        testID: "update-action-result",
      },
      {
        kind: "tap",
        stage: "reset runtime channel",
        testID: "action-reset-runtime-channel",
      },
      {
        contains: "runtime-channel -> reset",
        kind: "assertText",
        stage: "assert runtime channel reset",
        testID: "channel-action-result",
      },
    ],
  },
  {
    name: "numeric-cohort-rollout",
    wave: 3,
    steps: [
      { action: "launch", kind: "device", stage: "launch built-in app" },
      {
        kind: "control",
        pathName: "/e2e/capture-built-in-bundle-id",
        saveResultAs: "builtInBundleId",
        stage: "capture built-in bundle id",
      },
      {
        body: {
          channel: "production",
          marker: "numeric-cohort-detox",
          mode: "reset",
          rollout: 10,
          safeBundleIds: ["$builtInBundleId"],
          targetAppVersion: "1.0.x",
        },
        kind: "control",
        pathName: "/e2e/jobs/deploy-bundle",
        saveResultAs: "bundleId",
        stage: "deploy numeric cohort bundle",
      },
      {
        body: { bundleId: "$bundleId" },
        kind: "control",
        pathName: "/e2e/compute-rollout-sample",
        saveResultFieldsAs: {
          excludedCohort: "excludedCohort",
          includedCohort: "includedCohort",
        },
        stage: "compute rollout sample",
      },
      {
        kind: "typeText",
        stage: "enter included cohort",
        testID: "cohort-input",
        text: "$includedCohort",
      },
      {
        kind: "tap",
        stage: "apply included cohort",
        testID: "action-apply-cohort-input",
      },
      {
        contains: "set -> $includedCohort",
        kind: "assertText",
        stage: "assert included cohort applied",
        testID: "cohort-action-result",
      },
      {
        kind: "tap",
        stage: "install rollout update",
        testID: "action-install-current-channel-update",
      },
      {
        body: {
          bundleId: "$bundleId",
          relaunchLimit: 0,
          verificationPending: true,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait rollout metadata pending",
      },
      {
        contains: "current-channel",
        kind: "assertText",
        stage: "assert rollout action result",
        testID: "update-action-result",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload rollout update",
      },
      {
        body: { bundleId: "$bundleId", verificationPending: false },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait rollout metadata stable",
      },
      {
        contains: "$bundleId",
        kind: "assertText",
        stage: "assert rollout launch",
        testID: "runtime-bundle-id",
      },
      {
        kind: "typeText",
        stage: "enter excluded cohort",
        testID: "cohort-input",
        text: "$excludedCohort",
      },
      {
        kind: "tap",
        stage: "apply excluded cohort",
        testID: "action-apply-cohort-input",
      },
      {
        contains: "set -> $excludedCohort",
        kind: "assertText",
        stage: "assert excluded cohort applied",
        testID: "cohort-action-result",
      },
      {
        kind: "tap",
        stage: "install excluded cohort update",
        testID: "action-install-current-channel-update",
      },
      {
        kind: "control",
        pathName: "/e2e/assert-metadata-reset",
        stage: "assert excluded metadata reset",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload excluded cohort state",
      },
      {
        contains: "$builtInBundleId",
        kind: "assertText",
        stage: "assert excluded cohort built-in bundle",
        testID: "runtime-bundle-id",
      },
    ],
  },
  {
    name: "target-cohorts-only",
    wave: 3,
    steps: [
      {
        body: {
          channel: "production",
          marker: "target-cohorts-only-detox",
          mode: "reset",
          rollout: 0,
          safeBundleIds: [],
          targetAppVersion: "1.0.x",
          targetCohorts: ["qa"],
        },
        kind: "control",
        pathName: "/e2e/jobs/deploy-bundle",
        saveResultAs: "bundleId",
        stage: "deploy target cohort bundle",
      },
      {
        kind: "typeText",
        stage: "enter qa cohort",
        testID: "cohort-input",
        text: "qa",
      },
      {
        kind: "tap",
        stage: "apply qa cohort",
        testID: "action-apply-cohort-input",
      },
      {
        contains: "set -> qa",
        kind: "assertText",
        stage: "assert qa cohort applied",
        testID: "cohort-action-result",
      },
      {
        kind: "tap",
        stage: "install target cohort update",
        testID: "action-install-current-channel-update",
      },
      {
        body: {
          bundleId: "$bundleId",
          relaunchLimit: 0,
          verificationPending: true,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait target cohort metadata pending",
      },
      {
        contains: "current-channel -> installed $bundleId (UPDATE)",
        kind: "assertText",
        stage: "assert target cohort install result",
        testID: "update-action-result",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload target cohort update",
      },
      {
        body: { bundleId: "$bundleId", verificationPending: false },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait target cohort metadata stable",
      },
      {
        contains: "Current Launch Status: STABLE",
        kind: "assertText",
        stage: "assert target cohort launch",
        testID: "launch-status-result",
      },
    ],
  },
  {
    name: "target-cohorts-rollout-interaction",
    wave: 3,
    steps: [
      {
        body: {
          channel: "production",
          marker: "cohort-rollout-detox",
          mode: "reset",
          rollout: 50,
          safeBundleIds: [],
          targetAppVersion: "1.0.x",
          targetCohorts: ["qa"],
        },
        kind: "control",
        pathName: "/e2e/jobs/deploy-bundle",
        saveResultAs: "bundleId",
        stage: "deploy cohort rollout bundle",
      },
      {
        kind: "typeText",
        stage: "enter qa cohort",
        testID: "cohort-input",
        text: "qa",
      },
      {
        kind: "tap",
        stage: "apply qa cohort",
        testID: "action-apply-cohort-input",
      },
      {
        kind: "tap",
        stage: "install cohort rollout update",
        testID: "action-install-current-channel-update",
      },
      {
        body: { bundleId: "$bundleId" },
        kind: "control",
        pathName: "/e2e/assert-metadata-active",
        stage: "assert cohort rollout active",
      },
    ],
  },
  {
    name: "targeted-cohort-switchback",
    wave: 3,
    steps: [
      {
        body: {
          channel: "production",
          marker: "targeted-numeric-rollout-detox",
          mode: "reset",
          rollout: 10,
          safeBundleIds: [],
          targetAppVersion: "1.0.x",
        },
        kind: "control",
        pathName: "/e2e/jobs/deploy-bundle",
        saveResultAs: "numericBundleId",
        stage: "deploy numeric cohort bundle",
      },
      {
        body: { bundleId: "$numericBundleId" },
        kind: "control",
        pathName: "/e2e/compute-rollout-sample",
        saveResultFieldsAs: {
          includedCohort: "numericIncludedCohort",
          rolloutCohortCount: "numericRolloutCohortCount",
        },
        stage: "compute numeric rollout sample",
      },
      {
        body: {
          channel: "production",
          marker: "targeted-qa-detox",
          mode: "reset",
          rollout: 0,
          safeBundleIds: ["$numericBundleId"],
          targetAppVersion: "1.0.x",
          targetCohorts: ["qa"],
        },
        kind: "control",
        pathName: "/e2e/jobs/deploy-bundle",
        saveResultAs: "qaBundleId",
        stage: "deploy qa cohort bundle",
      },
      {
        kind: "typeText",
        stage: "enter numeric cohort",
        testID: "cohort-input",
        text: "$numericIncludedCohort",
      },
      {
        kind: "tap",
        stage: "apply numeric cohort",
        testID: "action-apply-cohort-input",
      },
      {
        contains: "set -> $numericIncludedCohort",
        kind: "assertText",
        stage: "assert numeric cohort applied",
        testID: "cohort-action-result",
      },
      {
        kind: "tap",
        stage: "install numeric cohort update",
        testID: "action-install-current-channel-update",
      },
      {
        body: {
          bundleId: "$numericBundleId",
          relaunchLimit: 0,
          verificationPending: true,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait numeric cohort metadata pending",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload numeric cohort update",
      },
      {
        body: {
          bundleId: "$numericBundleId",
          verificationPending: false,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait numeric cohort metadata stable",
      },
      {
        contains: "$numericBundleId",
        kind: "assertText",
        stage: "assert numeric cohort launch",
        testID: "runtime-bundle-id",
      },
      {
        kind: "typeText",
        stage: "enter qa cohort",
        testID: "cohort-input",
        text: "qa",
      },
      {
        kind: "tap",
        stage: "apply qa cohort",
        testID: "action-apply-cohort-input",
      },
      {
        kind: "tap",
        stage: "install qa cohort update",
        testID: "action-install-current-channel-update",
      },
      {
        body: {
          bundleId: "$qaBundleId",
          relaunchLimit: 0,
          verificationPending: true,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait qa cohort metadata pending",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload qa cohort update",
      },
      {
        body: { bundleId: "$qaBundleId", verificationPending: false },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait qa cohort metadata stable",
      },
      {
        contains: "$qaBundleId",
        kind: "assertText",
        stage: "assert qa cohort launch",
        testID: "runtime-bundle-id",
      },
      {
        kind: "typeText",
        stage: "restore numeric cohort",
        testID: "cohort-input",
        text: "$numericIncludedCohort",
      },
      {
        kind: "tap",
        stage: "apply restored numeric cohort",
        testID: "action-apply-cohort-input",
      },
      {
        contains: "set -> $numericIncludedCohort",
        kind: "assertText",
        stage: "assert numeric cohort restored",
        testID: "cohort-action-result",
      },
      {
        kind: "tap",
        stage: "install numeric cohort rollback",
        testID: "action-install-current-channel-update",
      },
      {
        body: {
          bundleId: "$numericBundleId",
          relaunchLimit: 0,
          verificationPending: true,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait numeric cohort rollback pending",
      },
      {
        action: "reload",
        kind: "device",
        stage: "reload numeric cohort rollback",
      },
      {
        body: {
          bundleId: "$numericBundleId",
          verificationPending: false,
        },
        kind: "control",
        pathName: "/e2e/jobs/wait-for-metadata",
        stage: "wait numeric cohort rollback stable",
      },
      {
        contains: "$numericBundleId",
        kind: "assertText",
        stage: "assert numeric cohort rollback launch",
        testID: "runtime-bundle-id",
      },
    ],
  },
];
