/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as E2eUpdateActionResultRouteImport } from './routes/e2e/update-action-result'
import { Route as E2eRuntimeReleaseStateRouteImport } from './routes/e2e/runtime-release-state'
import { Route as E2eRuntimeMarkerRouteImport } from './routes/e2e/runtime-marker'
import { Route as E2eRuntimeInitialCohortRouteImport } from './routes/e2e/runtime-initial-cohort'
import { Route as E2eRuntimeDefaultChannelRouteImport } from './routes/e2e/runtime-default-channel'
import { Route as E2eRuntimeCurrentCohortRouteImport } from './routes/e2e/runtime-current-cohort'
import { Route as E2eRuntimeCurrentChannelRouteImport } from './routes/e2e/runtime-current-channel'
import { Route as E2eRuntimeChannelSwitchedRouteImport } from './routes/e2e/runtime-channel-switched'
import { Route as E2eRuntimeBundleRouteImport } from './routes/e2e/runtime-bundle'
import { Route as E2eReadyRouteImport } from './routes/e2e/ready'
import { Route as E2eLaunchStatusRouteImport } from './routes/e2e/launch-status'
import { Route as E2eCrashHistoryCountRouteImport } from './routes/e2e/crash-history-count'
import { Route as E2eCohortActionResultRouteImport } from './routes/e2e/cohort-action-result'
import { Route as E2eChannelActionResultRouteImport } from './routes/e2e/channel-action-result'
import { Route as E2eInputRuntimeChannelRouteImport } from './routes/e2e/input/runtime-channel'
import { Route as E2eInputCohortRouteImport } from './routes/e2e/input/cohort'
import { Route as E2eActionSetCohortQaRouteImport } from './routes/e2e/action/set-cohort-qa'
import { Route as E2eActionRestoreInitialCohortRouteImport } from './routes/e2e/action/restore-initial-cohort'
import { Route as E2eActionResetRuntimeChannelRouteImport } from './routes/e2e/action/reset-runtime-channel'
import { Route as E2eActionReloadAppRouteImport } from './routes/e2e/action/reload-app'
import { Route as E2eActionRefreshRuntimeSnapshotRouteImport } from './routes/e2e/action/refresh-runtime-snapshot'
import { Route as E2eActionInstallRuntimeChannelUpdateRouteImport } from './routes/e2e/action/install-runtime-channel-update'
import { Route as E2eActionInstallFingerprintUpdateRouteImport } from './routes/e2e/action/install-fingerprint-update'
import { Route as E2eActionInstallCurrentChannelUpdateRouteImport } from './routes/e2e/action/install-current-channel-update'
import { Route as E2eActionClearCrashHistoryRouteImport } from './routes/e2e/action/clear-crash-history'
import { Route as E2eActionCaptureCurrentChannelUpdateRouteImport } from './routes/e2e/action/capture-current-channel-update'
import { Route as E2eActionApplyCohortInputRouteImport } from './routes/e2e/action/apply-cohort-input'
import { Route as E2eActionApplyCapturedUpdateRouteImport } from './routes/e2e/action/apply-captured-update'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eUpdateActionResultRoute = E2eUpdateActionResultRouteImport.update({
  id: '/e2e/update-action-result',
  path: '/e2e/update-action-result',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRuntimeReleaseStateRoute = E2eRuntimeReleaseStateRouteImport.update({
  id: '/e2e/runtime-release-state',
  path: '/e2e/runtime-release-state',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRuntimeMarkerRoute = E2eRuntimeMarkerRouteImport.update({
  id: '/e2e/runtime-marker',
  path: '/e2e/runtime-marker',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRuntimeInitialCohortRoute = E2eRuntimeInitialCohortRouteImport.update({
  id: '/e2e/runtime-initial-cohort',
  path: '/e2e/runtime-initial-cohort',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRuntimeDefaultChannelRoute =
  E2eRuntimeDefaultChannelRouteImport.update({
    id: '/e2e/runtime-default-channel',
    path: '/e2e/runtime-default-channel',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eRuntimeCurrentCohortRoute = E2eRuntimeCurrentCohortRouteImport.update({
  id: '/e2e/runtime-current-cohort',
  path: '/e2e/runtime-current-cohort',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eRuntimeCurrentChannelRoute =
  E2eRuntimeCurrentChannelRouteImport.update({
    id: '/e2e/runtime-current-channel',
    path: '/e2e/runtime-current-channel',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eRuntimeChannelSwitchedRoute =
  E2eRuntimeChannelSwitchedRouteImport.update({
    id: '/e2e/runtime-channel-switched',
    path: '/e2e/runtime-channel-switched',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eRuntimeBundleRoute = E2eRuntimeBundleRouteImport.update({
  id: '/e2e/runtime-bundle',
  path: '/e2e/runtime-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eReadyRoute = E2eReadyRouteImport.update({
  id: '/e2e/ready',
  path: '/e2e/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eLaunchStatusRoute = E2eLaunchStatusRouteImport.update({
  id: '/e2e/launch-status',
  path: '/e2e/launch-status',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eCrashHistoryCountRoute = E2eCrashHistoryCountRouteImport.update({
  id: '/e2e/crash-history-count',
  path: '/e2e/crash-history-count',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eCohortActionResultRoute = E2eCohortActionResultRouteImport.update({
  id: '/e2e/cohort-action-result',
  path: '/e2e/cohort-action-result',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eChannelActionResultRoute = E2eChannelActionResultRouteImport.update({
  id: '/e2e/channel-action-result',
  path: '/e2e/channel-action-result',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eInputRuntimeChannelRoute = E2eInputRuntimeChannelRouteImport.update({
  id: '/e2e/input/runtime-channel',
  path: '/e2e/input/runtime-channel',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eInputCohortRoute = E2eInputCohortRouteImport.update({
  id: '/e2e/input/cohort',
  path: '/e2e/input/cohort',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eActionSetCohortQaRoute = E2eActionSetCohortQaRouteImport.update({
  id: '/e2e/action/set-cohort-qa',
  path: '/e2e/action/set-cohort-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eActionRestoreInitialCohortRoute =
  E2eActionRestoreInitialCohortRouteImport.update({
    id: '/e2e/action/restore-initial-cohort',
    path: '/e2e/action/restore-initial-cohort',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionResetRuntimeChannelRoute =
  E2eActionResetRuntimeChannelRouteImport.update({
    id: '/e2e/action/reset-runtime-channel',
    path: '/e2e/action/reset-runtime-channel',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionReloadAppRoute = E2eActionReloadAppRouteImport.update({
  id: '/e2e/action/reload-app',
  path: '/e2e/action/reload-app',
  getParentRoute: () => rootRouteImport,
} as any)
const E2eActionRefreshRuntimeSnapshotRoute =
  E2eActionRefreshRuntimeSnapshotRouteImport.update({
    id: '/e2e/action/refresh-runtime-snapshot',
    path: '/e2e/action/refresh-runtime-snapshot',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionInstallRuntimeChannelUpdateRoute =
  E2eActionInstallRuntimeChannelUpdateRouteImport.update({
    id: '/e2e/action/install-runtime-channel-update',
    path: '/e2e/action/install-runtime-channel-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionInstallFingerprintUpdateRoute =
  E2eActionInstallFingerprintUpdateRouteImport.update({
    id: '/e2e/action/install-fingerprint-update',
    path: '/e2e/action/install-fingerprint-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionInstallCurrentChannelUpdateRoute =
  E2eActionInstallCurrentChannelUpdateRouteImport.update({
    id: '/e2e/action/install-current-channel-update',
    path: '/e2e/action/install-current-channel-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionClearCrashHistoryRoute =
  E2eActionClearCrashHistoryRouteImport.update({
    id: '/e2e/action/clear-crash-history',
    path: '/e2e/action/clear-crash-history',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionCaptureCurrentChannelUpdateRoute =
  E2eActionCaptureCurrentChannelUpdateRouteImport.update({
    id: '/e2e/action/capture-current-channel-update',
    path: '/e2e/action/capture-current-channel-update',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionApplyCohortInputRoute =
  E2eActionApplyCohortInputRouteImport.update({
    id: '/e2e/action/apply-cohort-input',
    path: '/e2e/action/apply-cohort-input',
    getParentRoute: () => rootRouteImport,
  } as any)
const E2eActionApplyCapturedUpdateRoute =
  E2eActionApplyCapturedUpdateRouteImport.update({
    id: '/e2e/action/apply-captured-update',
    path: '/e2e/action/apply-captured-update',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/e2e/channel-action-result': typeof E2eChannelActionResultRoute
  '/e2e/cohort-action-result': typeof E2eCohortActionResultRoute
  '/e2e/crash-history-count': typeof E2eCrashHistoryCountRoute
  '/e2e/launch-status': typeof E2eLaunchStatusRoute
  '/e2e/ready': typeof E2eReadyRoute
  '/e2e/runtime-bundle': typeof E2eRuntimeBundleRoute
  '/e2e/runtime-channel-switched': typeof E2eRuntimeChannelSwitchedRoute
  '/e2e/runtime-current-channel': typeof E2eRuntimeCurrentChannelRoute
  '/e2e/runtime-current-cohort': typeof E2eRuntimeCurrentCohortRoute
  '/e2e/runtime-default-channel': typeof E2eRuntimeDefaultChannelRoute
  '/e2e/runtime-initial-cohort': typeof E2eRuntimeInitialCohortRoute
  '/e2e/runtime-marker': typeof E2eRuntimeMarkerRoute
  '/e2e/runtime-release-state': typeof E2eRuntimeReleaseStateRoute
  '/e2e/update-action-result': typeof E2eUpdateActionResultRoute
  '/e2e/action/apply-captured-update': typeof E2eActionApplyCapturedUpdateRoute
  '/e2e/action/apply-cohort-input': typeof E2eActionApplyCohortInputRoute
  '/e2e/action/capture-current-channel-update': typeof E2eActionCaptureCurrentChannelUpdateRoute
  '/e2e/action/clear-crash-history': typeof E2eActionClearCrashHistoryRoute
  '/e2e/action/install-current-channel-update': typeof E2eActionInstallCurrentChannelUpdateRoute
  '/e2e/action/install-fingerprint-update': typeof E2eActionInstallFingerprintUpdateRoute
  '/e2e/action/install-runtime-channel-update': typeof E2eActionInstallRuntimeChannelUpdateRoute
  '/e2e/action/refresh-runtime-snapshot': typeof E2eActionRefreshRuntimeSnapshotRoute
  '/e2e/action/reload-app': typeof E2eActionReloadAppRoute
  '/e2e/action/reset-runtime-channel': typeof E2eActionResetRuntimeChannelRoute
  '/e2e/action/restore-initial-cohort': typeof E2eActionRestoreInitialCohortRoute
  '/e2e/action/set-cohort-qa': typeof E2eActionSetCohortQaRoute
  '/e2e/input/cohort': typeof E2eInputCohortRoute
  '/e2e/input/runtime-channel': typeof E2eInputRuntimeChannelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/e2e/channel-action-result': typeof E2eChannelActionResultRoute
  '/e2e/cohort-action-result': typeof E2eCohortActionResultRoute
  '/e2e/crash-history-count': typeof E2eCrashHistoryCountRoute
  '/e2e/launch-status': typeof E2eLaunchStatusRoute
  '/e2e/ready': typeof E2eReadyRoute
  '/e2e/runtime-bundle': typeof E2eRuntimeBundleRoute
  '/e2e/runtime-channel-switched': typeof E2eRuntimeChannelSwitchedRoute
  '/e2e/runtime-current-channel': typeof E2eRuntimeCurrentChannelRoute
  '/e2e/runtime-current-cohort': typeof E2eRuntimeCurrentCohortRoute
  '/e2e/runtime-default-channel': typeof E2eRuntimeDefaultChannelRoute
  '/e2e/runtime-initial-cohort': typeof E2eRuntimeInitialCohortRoute
  '/e2e/runtime-marker': typeof E2eRuntimeMarkerRoute
  '/e2e/runtime-release-state': typeof E2eRuntimeReleaseStateRoute
  '/e2e/update-action-result': typeof E2eUpdateActionResultRoute
  '/e2e/action/apply-captured-update': typeof E2eActionApplyCapturedUpdateRoute
  '/e2e/action/apply-cohort-input': typeof E2eActionApplyCohortInputRoute
  '/e2e/action/capture-current-channel-update': typeof E2eActionCaptureCurrentChannelUpdateRoute
  '/e2e/action/clear-crash-history': typeof E2eActionClearCrashHistoryRoute
  '/e2e/action/install-current-channel-update': typeof E2eActionInstallCurrentChannelUpdateRoute
  '/e2e/action/install-fingerprint-update': typeof E2eActionInstallFingerprintUpdateRoute
  '/e2e/action/install-runtime-channel-update': typeof E2eActionInstallRuntimeChannelUpdateRoute
  '/e2e/action/refresh-runtime-snapshot': typeof E2eActionRefreshRuntimeSnapshotRoute
  '/e2e/action/reload-app': typeof E2eActionReloadAppRoute
  '/e2e/action/reset-runtime-channel': typeof E2eActionResetRuntimeChannelRoute
  '/e2e/action/restore-initial-cohort': typeof E2eActionRestoreInitialCohortRoute
  '/e2e/action/set-cohort-qa': typeof E2eActionSetCohortQaRoute
  '/e2e/input/cohort': typeof E2eInputCohortRoute
  '/e2e/input/runtime-channel': typeof E2eInputRuntimeChannelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/e2e/channel-action-result': typeof E2eChannelActionResultRoute
  '/e2e/cohort-action-result': typeof E2eCohortActionResultRoute
  '/e2e/crash-history-count': typeof E2eCrashHistoryCountRoute
  '/e2e/launch-status': typeof E2eLaunchStatusRoute
  '/e2e/ready': typeof E2eReadyRoute
  '/e2e/runtime-bundle': typeof E2eRuntimeBundleRoute
  '/e2e/runtime-channel-switched': typeof E2eRuntimeChannelSwitchedRoute
  '/e2e/runtime-current-channel': typeof E2eRuntimeCurrentChannelRoute
  '/e2e/runtime-current-cohort': typeof E2eRuntimeCurrentCohortRoute
  '/e2e/runtime-default-channel': typeof E2eRuntimeDefaultChannelRoute
  '/e2e/runtime-initial-cohort': typeof E2eRuntimeInitialCohortRoute
  '/e2e/runtime-marker': typeof E2eRuntimeMarkerRoute
  '/e2e/runtime-release-state': typeof E2eRuntimeReleaseStateRoute
  '/e2e/update-action-result': typeof E2eUpdateActionResultRoute
  '/e2e/action/apply-captured-update': typeof E2eActionApplyCapturedUpdateRoute
  '/e2e/action/apply-cohort-input': typeof E2eActionApplyCohortInputRoute
  '/e2e/action/capture-current-channel-update': typeof E2eActionCaptureCurrentChannelUpdateRoute
  '/e2e/action/clear-crash-history': typeof E2eActionClearCrashHistoryRoute
  '/e2e/action/install-current-channel-update': typeof E2eActionInstallCurrentChannelUpdateRoute
  '/e2e/action/install-fingerprint-update': typeof E2eActionInstallFingerprintUpdateRoute
  '/e2e/action/install-runtime-channel-update': typeof E2eActionInstallRuntimeChannelUpdateRoute
  '/e2e/action/refresh-runtime-snapshot': typeof E2eActionRefreshRuntimeSnapshotRoute
  '/e2e/action/reload-app': typeof E2eActionReloadAppRoute
  '/e2e/action/reset-runtime-channel': typeof E2eActionResetRuntimeChannelRoute
  '/e2e/action/restore-initial-cohort': typeof E2eActionRestoreInitialCohortRoute
  '/e2e/action/set-cohort-qa': typeof E2eActionSetCohortQaRoute
  '/e2e/input/cohort': typeof E2eInputCohortRoute
  '/e2e/input/runtime-channel': typeof E2eInputRuntimeChannelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/e2e/channel-action-result'
    | '/e2e/cohort-action-result'
    | '/e2e/crash-history-count'
    | '/e2e/launch-status'
    | '/e2e/ready'
    | '/e2e/runtime-bundle'
    | '/e2e/runtime-channel-switched'
    | '/e2e/runtime-current-channel'
    | '/e2e/runtime-current-cohort'
    | '/e2e/runtime-default-channel'
    | '/e2e/runtime-initial-cohort'
    | '/e2e/runtime-marker'
    | '/e2e/runtime-release-state'
    | '/e2e/update-action-result'
    | '/e2e/action/apply-captured-update'
    | '/e2e/action/apply-cohort-input'
    | '/e2e/action/capture-current-channel-update'
    | '/e2e/action/clear-crash-history'
    | '/e2e/action/install-current-channel-update'
    | '/e2e/action/install-fingerprint-update'
    | '/e2e/action/install-runtime-channel-update'
    | '/e2e/action/refresh-runtime-snapshot'
    | '/e2e/action/reload-app'
    | '/e2e/action/reset-runtime-channel'
    | '/e2e/action/restore-initial-cohort'
    | '/e2e/action/set-cohort-qa'
    | '/e2e/input/cohort'
    | '/e2e/input/runtime-channel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/e2e/channel-action-result'
    | '/e2e/cohort-action-result'
    | '/e2e/crash-history-count'
    | '/e2e/launch-status'
    | '/e2e/ready'
    | '/e2e/runtime-bundle'
    | '/e2e/runtime-channel-switched'
    | '/e2e/runtime-current-channel'
    | '/e2e/runtime-current-cohort'
    | '/e2e/runtime-default-channel'
    | '/e2e/runtime-initial-cohort'
    | '/e2e/runtime-marker'
    | '/e2e/runtime-release-state'
    | '/e2e/update-action-result'
    | '/e2e/action/apply-captured-update'
    | '/e2e/action/apply-cohort-input'
    | '/e2e/action/capture-current-channel-update'
    | '/e2e/action/clear-crash-history'
    | '/e2e/action/install-current-channel-update'
    | '/e2e/action/install-fingerprint-update'
    | '/e2e/action/install-runtime-channel-update'
    | '/e2e/action/refresh-runtime-snapshot'
    | '/e2e/action/reload-app'
    | '/e2e/action/reset-runtime-channel'
    | '/e2e/action/restore-initial-cohort'
    | '/e2e/action/set-cohort-qa'
    | '/e2e/input/cohort'
    | '/e2e/input/runtime-channel'
  id:
    | '__root__'
    | '/'
    | '/e2e/channel-action-result'
    | '/e2e/cohort-action-result'
    | '/e2e/crash-history-count'
    | '/e2e/launch-status'
    | '/e2e/ready'
    | '/e2e/runtime-bundle'
    | '/e2e/runtime-channel-switched'
    | '/e2e/runtime-current-channel'
    | '/e2e/runtime-current-cohort'
    | '/e2e/runtime-default-channel'
    | '/e2e/runtime-initial-cohort'
    | '/e2e/runtime-marker'
    | '/e2e/runtime-release-state'
    | '/e2e/update-action-result'
    | '/e2e/action/apply-captured-update'
    | '/e2e/action/apply-cohort-input'
    | '/e2e/action/capture-current-channel-update'
    | '/e2e/action/clear-crash-history'
    | '/e2e/action/install-current-channel-update'
    | '/e2e/action/install-fingerprint-update'
    | '/e2e/action/install-runtime-channel-update'
    | '/e2e/action/refresh-runtime-snapshot'
    | '/e2e/action/reload-app'
    | '/e2e/action/reset-runtime-channel'
    | '/e2e/action/restore-initial-cohort'
    | '/e2e/action/set-cohort-qa'
    | '/e2e/input/cohort'
    | '/e2e/input/runtime-channel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  E2eChannelActionResultRoute: typeof E2eChannelActionResultRoute
  E2eCohortActionResultRoute: typeof E2eCohortActionResultRoute
  E2eCrashHistoryCountRoute: typeof E2eCrashHistoryCountRoute
  E2eLaunchStatusRoute: typeof E2eLaunchStatusRoute
  E2eReadyRoute: typeof E2eReadyRoute
  E2eRuntimeBundleRoute: typeof E2eRuntimeBundleRoute
  E2eRuntimeChannelSwitchedRoute: typeof E2eRuntimeChannelSwitchedRoute
  E2eRuntimeCurrentChannelRoute: typeof E2eRuntimeCurrentChannelRoute
  E2eRuntimeCurrentCohortRoute: typeof E2eRuntimeCurrentCohortRoute
  E2eRuntimeDefaultChannelRoute: typeof E2eRuntimeDefaultChannelRoute
  E2eRuntimeInitialCohortRoute: typeof E2eRuntimeInitialCohortRoute
  E2eRuntimeMarkerRoute: typeof E2eRuntimeMarkerRoute
  E2eRuntimeReleaseStateRoute: typeof E2eRuntimeReleaseStateRoute
  E2eUpdateActionResultRoute: typeof E2eUpdateActionResultRoute
  E2eActionApplyCapturedUpdateRoute: typeof E2eActionApplyCapturedUpdateRoute
  E2eActionApplyCohortInputRoute: typeof E2eActionApplyCohortInputRoute
  E2eActionCaptureCurrentChannelUpdateRoute: typeof E2eActionCaptureCurrentChannelUpdateRoute
  E2eActionClearCrashHistoryRoute: typeof E2eActionClearCrashHistoryRoute
  E2eActionInstallCurrentChannelUpdateRoute: typeof E2eActionInstallCurrentChannelUpdateRoute
  E2eActionInstallFingerprintUpdateRoute: typeof E2eActionInstallFingerprintUpdateRoute
  E2eActionInstallRuntimeChannelUpdateRoute: typeof E2eActionInstallRuntimeChannelUpdateRoute
  E2eActionRefreshRuntimeSnapshotRoute: typeof E2eActionRefreshRuntimeSnapshotRoute
  E2eActionReloadAppRoute: typeof E2eActionReloadAppRoute
  E2eActionResetRuntimeChannelRoute: typeof E2eActionResetRuntimeChannelRoute
  E2eActionRestoreInitialCohortRoute: typeof E2eActionRestoreInitialCohortRoute
  E2eActionSetCohortQaRoute: typeof E2eActionSetCohortQaRoute
  E2eInputCohortRoute: typeof E2eInputCohortRoute
  E2eInputRuntimeChannelRoute: typeof E2eInputRuntimeChannelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/update-action-result': {
      id: '/e2e/update-action-result'
      path: '/e2e/update-action-result'
      fullPath: '/e2e/update-action-result'
      preLoaderRoute: typeof E2eUpdateActionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-release-state': {
      id: '/e2e/runtime-release-state'
      path: '/e2e/runtime-release-state'
      fullPath: '/e2e/runtime-release-state'
      preLoaderRoute: typeof E2eRuntimeReleaseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-marker': {
      id: '/e2e/runtime-marker'
      path: '/e2e/runtime-marker'
      fullPath: '/e2e/runtime-marker'
      preLoaderRoute: typeof E2eRuntimeMarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-initial-cohort': {
      id: '/e2e/runtime-initial-cohort'
      path: '/e2e/runtime-initial-cohort'
      fullPath: '/e2e/runtime-initial-cohort'
      preLoaderRoute: typeof E2eRuntimeInitialCohortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-default-channel': {
      id: '/e2e/runtime-default-channel'
      path: '/e2e/runtime-default-channel'
      fullPath: '/e2e/runtime-default-channel'
      preLoaderRoute: typeof E2eRuntimeDefaultChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-current-cohort': {
      id: '/e2e/runtime-current-cohort'
      path: '/e2e/runtime-current-cohort'
      fullPath: '/e2e/runtime-current-cohort'
      preLoaderRoute: typeof E2eRuntimeCurrentCohortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-current-channel': {
      id: '/e2e/runtime-current-channel'
      path: '/e2e/runtime-current-channel'
      fullPath: '/e2e/runtime-current-channel'
      preLoaderRoute: typeof E2eRuntimeCurrentChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-channel-switched': {
      id: '/e2e/runtime-channel-switched'
      path: '/e2e/runtime-channel-switched'
      fullPath: '/e2e/runtime-channel-switched'
      preLoaderRoute: typeof E2eRuntimeChannelSwitchedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/runtime-bundle': {
      id: '/e2e/runtime-bundle'
      path: '/e2e/runtime-bundle'
      fullPath: '/e2e/runtime-bundle'
      preLoaderRoute: typeof E2eRuntimeBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/ready': {
      id: '/e2e/ready'
      path: '/e2e/ready'
      fullPath: '/e2e/ready'
      preLoaderRoute: typeof E2eReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/launch-status': {
      id: '/e2e/launch-status'
      path: '/e2e/launch-status'
      fullPath: '/e2e/launch-status'
      preLoaderRoute: typeof E2eLaunchStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/crash-history-count': {
      id: '/e2e/crash-history-count'
      path: '/e2e/crash-history-count'
      fullPath: '/e2e/crash-history-count'
      preLoaderRoute: typeof E2eCrashHistoryCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/cohort-action-result': {
      id: '/e2e/cohort-action-result'
      path: '/e2e/cohort-action-result'
      fullPath: '/e2e/cohort-action-result'
      preLoaderRoute: typeof E2eCohortActionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/channel-action-result': {
      id: '/e2e/channel-action-result'
      path: '/e2e/channel-action-result'
      fullPath: '/e2e/channel-action-result'
      preLoaderRoute: typeof E2eChannelActionResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/input/runtime-channel': {
      id: '/e2e/input/runtime-channel'
      path: '/e2e/input/runtime-channel'
      fullPath: '/e2e/input/runtime-channel'
      preLoaderRoute: typeof E2eInputRuntimeChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/input/cohort': {
      id: '/e2e/input/cohort'
      path: '/e2e/input/cohort'
      fullPath: '/e2e/input/cohort'
      preLoaderRoute: typeof E2eInputCohortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/set-cohort-qa': {
      id: '/e2e/action/set-cohort-qa'
      path: '/e2e/action/set-cohort-qa'
      fullPath: '/e2e/action/set-cohort-qa'
      preLoaderRoute: typeof E2eActionSetCohortQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/restore-initial-cohort': {
      id: '/e2e/action/restore-initial-cohort'
      path: '/e2e/action/restore-initial-cohort'
      fullPath: '/e2e/action/restore-initial-cohort'
      preLoaderRoute: typeof E2eActionRestoreInitialCohortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/reset-runtime-channel': {
      id: '/e2e/action/reset-runtime-channel'
      path: '/e2e/action/reset-runtime-channel'
      fullPath: '/e2e/action/reset-runtime-channel'
      preLoaderRoute: typeof E2eActionResetRuntimeChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/reload-app': {
      id: '/e2e/action/reload-app'
      path: '/e2e/action/reload-app'
      fullPath: '/e2e/action/reload-app'
      preLoaderRoute: typeof E2eActionReloadAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/refresh-runtime-snapshot': {
      id: '/e2e/action/refresh-runtime-snapshot'
      path: '/e2e/action/refresh-runtime-snapshot'
      fullPath: '/e2e/action/refresh-runtime-snapshot'
      preLoaderRoute: typeof E2eActionRefreshRuntimeSnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/install-runtime-channel-update': {
      id: '/e2e/action/install-runtime-channel-update'
      path: '/e2e/action/install-runtime-channel-update'
      fullPath: '/e2e/action/install-runtime-channel-update'
      preLoaderRoute: typeof E2eActionInstallRuntimeChannelUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/install-fingerprint-update': {
      id: '/e2e/action/install-fingerprint-update'
      path: '/e2e/action/install-fingerprint-update'
      fullPath: '/e2e/action/install-fingerprint-update'
      preLoaderRoute: typeof E2eActionInstallFingerprintUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/install-current-channel-update': {
      id: '/e2e/action/install-current-channel-update'
      path: '/e2e/action/install-current-channel-update'
      fullPath: '/e2e/action/install-current-channel-update'
      preLoaderRoute: typeof E2eActionInstallCurrentChannelUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/clear-crash-history': {
      id: '/e2e/action/clear-crash-history'
      path: '/e2e/action/clear-crash-history'
      fullPath: '/e2e/action/clear-crash-history'
      preLoaderRoute: typeof E2eActionClearCrashHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/capture-current-channel-update': {
      id: '/e2e/action/capture-current-channel-update'
      path: '/e2e/action/capture-current-channel-update'
      fullPath: '/e2e/action/capture-current-channel-update'
      preLoaderRoute: typeof E2eActionCaptureCurrentChannelUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/apply-cohort-input': {
      id: '/e2e/action/apply-cohort-input'
      path: '/e2e/action/apply-cohort-input'
      fullPath: '/e2e/action/apply-cohort-input'
      preLoaderRoute: typeof E2eActionApplyCohortInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e2e/action/apply-captured-update': {
      id: '/e2e/action/apply-captured-update'
      path: '/e2e/action/apply-captured-update'
      fullPath: '/e2e/action/apply-captured-update'
      preLoaderRoute: typeof E2eActionApplyCapturedUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  E2eChannelActionResultRoute: E2eChannelActionResultRoute,
  E2eCohortActionResultRoute: E2eCohortActionResultRoute,
  E2eCrashHistoryCountRoute: E2eCrashHistoryCountRoute,
  E2eLaunchStatusRoute: E2eLaunchStatusRoute,
  E2eReadyRoute: E2eReadyRoute,
  E2eRuntimeBundleRoute: E2eRuntimeBundleRoute,
  E2eRuntimeChannelSwitchedRoute: E2eRuntimeChannelSwitchedRoute,
  E2eRuntimeCurrentChannelRoute: E2eRuntimeCurrentChannelRoute,
  E2eRuntimeCurrentCohortRoute: E2eRuntimeCurrentCohortRoute,
  E2eRuntimeDefaultChannelRoute: E2eRuntimeDefaultChannelRoute,
  E2eRuntimeInitialCohortRoute: E2eRuntimeInitialCohortRoute,
  E2eRuntimeMarkerRoute: E2eRuntimeMarkerRoute,
  E2eRuntimeReleaseStateRoute: E2eRuntimeReleaseStateRoute,
  E2eUpdateActionResultRoute: E2eUpdateActionResultRoute,
  E2eActionApplyCapturedUpdateRoute: E2eActionApplyCapturedUpdateRoute,
  E2eActionApplyCohortInputRoute: E2eActionApplyCohortInputRoute,
  E2eActionCaptureCurrentChannelUpdateRoute:
    E2eActionCaptureCurrentChannelUpdateRoute,
  E2eActionClearCrashHistoryRoute: E2eActionClearCrashHistoryRoute,
  E2eActionInstallCurrentChannelUpdateRoute:
    E2eActionInstallCurrentChannelUpdateRoute,
  E2eActionInstallFingerprintUpdateRoute:
    E2eActionInstallFingerprintUpdateRoute,
  E2eActionInstallRuntimeChannelUpdateRoute:
    E2eActionInstallRuntimeChannelUpdateRoute,
  E2eActionRefreshRuntimeSnapshotRoute: E2eActionRefreshRuntimeSnapshotRoute,
  E2eActionReloadAppRoute: E2eActionReloadAppRoute,
  E2eActionResetRuntimeChannelRoute: E2eActionResetRuntimeChannelRoute,
  E2eActionRestoreInitialCohortRoute: E2eActionRestoreInitialCohortRoute,
  E2eActionSetCohortQaRoute: E2eActionSetCohortQaRoute,
  E2eInputCohortRoute: E2eInputCohortRoute,
  E2eInputRuntimeChannelRoute: E2eInputRuntimeChannelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
