import type {
  StorageProviderMatrixCell,
  StorageProviderMatrixCellInput,
} from "./capabilityMatrixTypes";

const REQUIRED_OPERATIONS = Object.freeze({
  put: true,
  head: true,
  get: true,
  delete: true,
});

const runtime = (
  observations: StorageProviderMatrixCellInput["observations"],
  streamLifetime: StorageProviderMatrixCellInput["streamLifetime"],
) =>
  Object.freeze({
    observations: Object.freeze(observations),
    literalCache: "allowed" as const,
    taggedCache: "forbidden" as const,
    streamLifetime,
  });

const cell = (
  input: StorageProviderMatrixCellInput,
): StorageProviderMatrixCell => {
  const { observations, streamLifetime, ...attributes } = input;
  return Object.freeze({
    ...attributes,
    contractVersion: 2 as const,
    operations: REQUIRED_OPERATIONS,
    runtime: runtime(observations, streamLifetime),
  });
};

export const STORAGE_V2_PROVIDER_MATRIX = [
  cell({
    id: "mock-neutral",
    entry: "@hot-updater/mock/storage",
    entryTarget: "neutral",
    target: "node",
    acceptedTargets: ["node", "worker", "functions", "edge"],
    protocol: "storage",
    createOnly: true,
    range: true,
    delivery: "unsupported",
    list: "unsupported",
    ownership: "borrowed-direct",
    observations: ["context", "stream"],
    streamLifetime: "borrowed",
  }),
  cell({
    id: "mock-node",
    entry: "@hot-updater/mock/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "storage",
    createOnly: true,
    range: true,
    delivery: "unsupported",
    list: "unsupported",
    ownership: "borrowed-direct",
    observations: ["context", "stream"],
    streamLifetime: "borrowed",
  }),
  cell({
    id: "aws-node",
    entry: "@hot-updater/aws/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "s3",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: ["endpoint", "credential", "bucket", "client", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "aws-lambda",
    entry: "@hot-updater/aws/storage/lambda",
    entryTarget: "functions",
    target: "functions",
    acceptedTargets: ["functions"],
    protocol: "s3",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: ["endpoint", "credential", "bucket", "client", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "cloudflare-node",
    entry: "@hot-updater/cloudflare/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "r2",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: ["endpoint", "credential", "bucket", "client", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "cloudflare-worker",
    entry: "@hot-updater/cloudflare/storage/worker",
    entryTarget: "worker",
    target: "worker",
    acceptedTargets: ["worker"],
    protocol: "r2",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "borrowed-direct",
    observations: ["binding", "bucket", "stream"],
    streamLifetime: "borrowed",
  }),
  cell({
    id: "firebase-node",
    entry: "@hot-updater/firebase/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "gs",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: ["credential", "bucket", "client", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "firebase-functions",
    entry: "@hot-updater/firebase/storage/functions",
    entryTarget: "functions",
    target: "functions",
    acceptedTargets: ["functions"],
    protocol: "gs",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: ["credential", "bucket", "client", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "supabase-node",
    entry: "@hot-updater/supabase/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "supabase-storage",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: [
      "endpoint",
      "credential",
      "header",
      "bucket",
      "client",
      "stream",
    ],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "supabase-edge",
    entry: "@hot-updater/supabase/storage/edge",
    entryTarget: "edge",
    target: "edge",
    acceptedTargets: ["worker", "edge"],
    protocol: "supabase-storage",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "owned-factory",
    observations: [
      "endpoint",
      "credential",
      "header",
      "bucket",
      "client",
      "stream",
    ],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "standalone-neutral",
    entry: "@hot-updater/standalone/storage",
    entryTarget: "neutral",
    target: "node",
    acceptedTargets: ["node", "worker", "functions", "edge"],
    protocol: "http",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "remote-mount",
    observations: ["endpoint", "header", "stream"],
    streamLifetime: "response-owned",
  }),
  cell({
    id: "standalone-node",
    entry: "@hot-updater/standalone/storage/node",
    entryTarget: "node",
    target: "node",
    acceptedTargets: ["node"],
    protocol: "http",
    createOnly: true,
    range: true,
    delivery: "supported",
    list: "unsupported",
    ownership: "remote-mount",
    observations: ["endpoint", "header", "stream"],
    streamLifetime: "response-owned",
  }),
] as const satisfies readonly StorageProviderMatrixCell[];
