// Generated by Wrangler
// After adding bindings to `wrangler.json`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    BUCKET: R2Bucket;
    BUCKET_NAME: string;
    PUBLIC_BASE_URL: string;
    STORAGE_DELIVERY_SIGNING_KEY: string;
  }
}

interface Env extends Cloudflare.Env {}
