import fs from "fs/promises";

import { p } from "./prompts";

/** Where `hot-updater init` writes a managed server's plugin list. */
export const HOT_UPDATER_PLUGINS_PATH = "hotUpdater.plugins.ts";

/**
 * The plugins file for a managed provider: a re-export of the fixed list its
 * package ships, which its prebuilt server runs too.
 */
export const renderHotUpdaterPlugins = (pkg: string): string =>
  [
    "// Generated by `hot-updater init`. The managed server runs these plugins,",
    `// and ${pkg} fixes the list, so the server, CLI, and console agree.`,
    `export { plugins } from "${pkg}";`,
    "",
  ].join("\n");

export type WriteHotUpdaterPluginsResult =
  | {
      readonly status: "created" | "unchanged";
      readonly path: string;
    }
  | {
      readonly status: "skipped";
      readonly path: string;
      readonly reason: string;
    };

/** Writes the plugins file; an existing file that differs is kept. */
export const writeHotUpdaterPlugins = async (
  pkg: string,
  filePath = HOT_UPDATER_PLUGINS_PATH,
): Promise<WriteHotUpdaterPluginsResult> => {
  const text = renderHotUpdaterPlugins(pkg);
  const existingText = await fs.readFile(filePath, "utf-8").catch((error) => {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return null;
    }
    throw error;
  });

  if (existingText === null) {
    await fs.writeFile(filePath, text, "utf-8");
    return { status: "created", path: filePath };
  }
  if (existingText === text) {
    return { status: "unchanged", path: filePath };
  }
  return {
    status: "skipped",
    path: filePath,
    reason: `it does not re-export the plugins ${pkg} runs; replace it with \`export { plugins } from "${pkg}";\``,
  };
};

/** Writes the plugins file for `pkg` and reports what happened. */
export const generateHotUpdaterPlugins = async (
  pkg: string,
  filePath = HOT_UPDATER_PLUGINS_PATH,
): Promise<WriteHotUpdaterPluginsResult> => {
  const result = await writeHotUpdaterPlugins(pkg, filePath);
  if (result.status === "created") {
    p.log.success(`Generated '${filePath}' with the plugins the server runs.`);
  } else if (result.status === "skipped") {
    p.log.warn(`Kept existing '${filePath}' unchanged: ${result.reason}`);
  }
  return result;
};
