import type { PluginObj } from "@babel/core";
import type { NodePath } from "@babel/traverse";
import type * as babelTypes from "@babel/types";
import { colors } from "@hot-updater/cli-tools";
import fs from "fs";
import path from "path";
import { uuidv7 } from "uuidv7";

const NIL_UUID = "00000000-0000-0000-0000-000000000000";

const getBundleId = () => {
  const buildOutDir = process.env["BUILD_OUT_DIR"];
  if (!buildOutDir) {
    return NIL_UUID;
  }

  const bundleIdPath = path.join(buildOutDir, "BUNDLE_ID");

  let bundleId = uuidv7();

  if (fs.existsSync(bundleIdPath)) {
    bundleId = fs.readFileSync(bundleIdPath, "utf-8");
  } else {
    fs.writeFileSync(bundleIdPath, bundleId);
    console.log(colors.green(`[HotUpdater] Generated bundle ID: ${bundleId}`));
  }

  return bundleId;
};

/**
 * Hot Updater Babel Plugin
 *
 * This plugin handles two transformations:
 * 1. Replaces __HOT_UPDATER_BUNDLE_ID with the actual bundle ID
 * 2. Transforms Expo DOM component filePath to overrideUri for OTA updates
 */
export default function ({
  types: t,
}: {
  types: typeof babelTypes;
}): PluginObj {
  const bundleId = getBundleId();
  return {
    name: "hot-updater-babel-plugin",
    visitor: {
      Identifier(path: NodePath<babelTypes.Identifier>) {
        // Transform __HOT_UPDATER_BUNDLE_ID to actual bundle ID
        if (path.node.name === "__HOT_UPDATER_BUNDLE_ID") {
          path.replaceWith(t.stringLiteral(bundleId));
        }
      },
      ObjectExpression(path) {
        // Transform Expo DOM components (generated by "use dom" directive)
        // Find filePath property in object expressions
        const filePathProp = path.node.properties.find(
          (prop) =>
            t.isObjectProperty(prop) &&
            t.isIdentifier(prop.key, { name: "filePath" }) &&
            t.isStringLiteral(prop.value) &&
            prop.value.value.endsWith(".html"),
        );

        if (!filePathProp || !t.isObjectProperty(filePathProp)) {
          return;
        }

        const filePathValue = filePathProp.value;
        if (!t.isStringLiteral(filePathValue)) {
          return;
        }

        const fileName = filePathValue.value;

        // Find if there's a spread element (e.g., ...f)
        const spreadElement = path.node.properties.find((prop) =>
          t.isSpreadElement(prop),
        ) as babelTypes.SpreadElement | undefined;

        let domObjectExpression: babelTypes.ObjectExpression;

        // Create ES5-compatible globalThis check and HotUpdaterGetBaseURL call
        // (typeof globalThis !== "undefined" && globalThis.HotUpdaterGetBaseURL) ? globalThis.HotUpdaterGetBaseURL() : void 0
        const safeGetBaseURL = t.conditionalExpression(
          t.logicalExpression(
            "&&",
            t.binaryExpression(
              "!==",
              t.unaryExpression("typeof", t.identifier("globalThis"), true),
              t.stringLiteral("undefined"),
            ),
            t.memberExpression(
              t.identifier("globalThis"),
              t.identifier("HotUpdaterGetBaseURL"),
            ),
          ),
          t.callExpression(
            t.memberExpression(
              t.identifier("globalThis"),
              t.identifier("HotUpdaterGetBaseURL"),
            ),
            [],
          ),
          t.unaryExpression("void", t.numericLiteral(0), true),
        );

        if (spreadElement && t.isIdentifier(spreadElement.argument)) {
          // Create: dom: { ...f.dom, overrideUri: [...].join("/") }
          domObjectExpression = t.objectExpression([
            t.spreadElement(
              t.memberExpression(spreadElement.argument, t.identifier("dom")),
            ),
            t.objectProperty(
              t.identifier("overrideUri"),
              t.callExpression(
                t.memberExpression(
                  t.arrayExpression([
                    safeGetBaseURL,
                    t.stringLiteral("www.bundle"),
                    t.stringLiteral(fileName),
                  ]),
                  t.identifier("join"),
                ),
                [t.stringLiteral("/")],
              ),
            ),
          ]);
        } else {
          // Create: dom: { overrideUri: [...].join("/") }
          domObjectExpression = t.objectExpression([
            t.objectProperty(
              t.identifier("overrideUri"),
              t.callExpression(
                t.memberExpression(
                  t.arrayExpression([
                    safeGetBaseURL,
                    t.stringLiteral("www.bundle"),
                    t.stringLiteral(fileName),
                  ]),
                  t.identifier("join"),
                ),
                [t.stringLiteral("/")],
              ),
            ),
          ]);
        }

        const domProperty = t.objectProperty(
          t.identifier("dom"),
          domObjectExpression,
        );

        // Replace filePath with dom property
        const propIndex = path.node.properties.indexOf(filePathProp);
        path.node.properties.splice(propIndex, 1, domProperty);
      },
    },
  };
}
