import {
  bigint,
  boolean,
  doublePrecision,
  integer,
  jsonb,
  pgTable,
  text,
  varchar,
} from "drizzle-orm/pg-core";

const bundles = pgTable("bundles", {
  id: text("id").primaryKey(),
  platform: text("platform").notNull(),
  git_commit_hash: text("git_commit_hash"),
  metadata: jsonb("metadata").notNull(),
  manifest_storage_uri: text("manifest_storage_uri").notNull(),
  manifest_file_hash: text("manifest_file_hash").notNull(),
  asset_base_storage_uri: text("asset_base_storage_uri").notNull(),
});
const channels = pgTable("channels", {
  id: text("id").primaryKey(),
  name: text("name").notNull().unique(),
});
const releases = pgTable("releases", {
  id: text("id").primaryKey(),
  revision: integer("revision").notNull(),
  scope_key: text("scope_key").notNull(),
  channel_id: text("channel_id").notNull(),
  platform: text("platform").notNull(),
  kind: text("kind").notNull(),
  bundle_id: text("bundle_id"),
  strategy: text("strategy").notNull(),
  target_app_version: text("target_app_version"),
  fingerprint_hash: text("fingerprint_hash"),
  enabled: boolean("enabled").notNull(),
  should_force_update: boolean("should_force_update").notNull(),
  message: text("message"),
  rollout_cohort_count: integer("rollout_cohort_count").notNull(),
  target_cohorts: jsonb("target_cohorts").notNull(),
  operation: text("operation").notNull(),
  source_release_id: text("source_release_id"),
  created_at_ms: integer("created_at_ms").notNull(),
  updated_at_ms: integer("updated_at_ms").notNull(),
});
const releaseCatalogs = pgTable("release_catalogs", {
  scope_key: text("scope_key").primaryKey(),
  catalog_id: text("catalog_id").notNull(),
  strategy: text("strategy").notNull(),
  channel_id: text("channel_id").notNull(),
  channel_key: text("channel_key").notNull(),
  platform: text("platform").notNull(),
  fingerprint_hash: text("fingerprint_hash"),
  generation: integer("generation").notNull(),
  payload: text("payload").notNull(),
  catalog_hash: text("catalog_hash").notNull(),
  byte_size: integer("byte_size").notNull(),
  is_tombstone: boolean("is_tombstone").notNull(),
  updated_at_ms: integer("updated_at_ms").notNull(),
});
const bundlePatches = pgTable("bundle_patches", {
  id: varchar("id", { length: 255 }).primaryKey(),
  bundle_id: text("bundle_id").notNull(),
  base_bundle_id: text("base_bundle_id").notNull(),
  base_file_hash: text("base_file_hash").notNull(),
  patch_file_hash: text("patch_file_hash").notNull(),
  patch_storage_uri: text("patch_storage_uri").notNull(),
  byte_size: doublePrecision("byte_size").notNull(),
  order_index: integer("order_index").notNull(),
});
const bundleEvents = pgTable("bundle_events", {
  id: text("id").primaryKey(),
  type: text("type").notNull(),
  install_id: text("install_id").notNull(),
  user_id: text("user_id"),
  metadata: jsonb("metadata").notNull(),
  from_release_id: text("from_release_id"),
  from_bundle_id: text("from_bundle_id"),
  to_release_id: text("to_release_id"),
  to_bundle_id: text("to_bundle_id").notNull(),
  platform: text("platform").notNull(),
  app_version: text("app_version").notNull(),
  channel: text("channel").notNull(),

  received_at_ms: integer("received_at_ms").notNull(),
});
const bundleEventHeads = pgTable("bundle_event_heads", {
  install_id: text("install_id").primaryKey(),
  id: text("id").notNull(),
  received_at_ms: integer("received_at_ms").notNull(),
  user_id: text("user_id"),
  platform: text("platform").notNull(),
  channel: text("channel").notNull(),
  type: text("type").notNull(),
  from_bundle_id: text("from_bundle_id"),
  to_bundle_id: text("to_bundle_id").notNull(),
  current_release_id: text("current_release_id"),
  app_version: text("app_version").notNull(),
});
const insightsOverview = pgTable("insights_overview", {
  id: text("id").primaryKey(),
  scope_kind: text("scope_kind").notNull(),
  release_kind: text("release_kind").notNull(),
  release_id: text("release_id").notNull(),
  channel: text("channel").notNull(),
  platform: text("platform").notNull(),
  app_version_kind: text("app_version_kind").notNull(),
  app_version: text("app_version").notNull(),
  period_kind: text("period_kind").notNull(),
  bucket_start_ms: doublePrecision("bucket_start_ms").notNull(),
  downloads: bigint("downloads", { mode: "number" }).notNull(),
  launches: bigint("launches", { mode: "number" }).notNull(),
  failed_launches: bigint("failed_launches", { mode: "number" }).notNull(),
  latest_installations: bigint("latest_installations", {
    mode: "number",
  }).notNull(),
  launch_users: text("launch_users"),
  activity_users: text("activity_users"),
});
const apiKeys = pgTable("api_keys", {
  id: text("id").primaryKey(),
  hash: text("hash").notNull().unique(),
  name: text("name").notNull(),
  prefix: text("prefix").notNull(),
  role: text("role").notNull(),
  created_at_ms: integer("created_at_ms").notNull(),
  revoked_at_ms: integer("revoked_at_ms"),
});
export const schema = {
  bundle_events: bundleEvents,
  bundle_event_heads: bundleEventHeads,
  insights_overview: insightsOverview,

  bundle_patches: bundlePatches,
  bundles,
  channels,
  api_keys: apiKeys,
  release_catalogs: releaseCatalogs,
  releases,
};
