import { mockDatabase, mockStorage } from "@hot-updater/mock";

const now = new Date();

function hoursAgo(hours: number): string {
  return new Date(now.getTime() - hours * 60 * 60 * 1000).toISOString();
}

function randomDeviceId(): string {
  return `device-${Math.random().toString(36).substring(2, 10)}`;
}

const bundles = [
  {
    id: "0195c7c0-8bbe-7885-ae58-09bcab7f7a87",
    enabled: true,
    shouldForceUpdate: false,
    fileHash: "abc123hash",
    gitCommitHash: "a1b2c3d",
    platform: "ios" as const,
    targetAppVersion: "1.2.x",
    message: "Fix: Crash on startup for iPhone 12",
    channel: "production",
    storageUri: "s3://hot-updater/0195c7c0-8bbe-7885-ae58-09bcab7f7a87.zip",
    fingerprintHash: "fp-abc123",
    rolloutPercentage: 100,
  },
  {
    id: "0195c7bf-e8f2-7546-8aba-8bad8243afeb",
    enabled: true,
    shouldForceUpdate: false,
    fileHash: "def456hash",
    gitCommitHash: "e4f5g6h",
    platform: "ios" as const,
    targetAppVersion: "1.2.x",
    message: "Feature: New onboarding flow",
    channel: "production",
    storageUri: "s3://hot-updater/0195c7bf-e8f2-7546-8aba-8bad8243afeb.zip",
    fingerprintHash: "fp-def456",
    rolloutPercentage: 50,
  },
  {
    id: "0195c7bf-d48d-7785-9295-15b154d271a3",
    enabled: true,
    shouldForceUpdate: true,
    fileHash: "ghi789hash",
    gitCommitHash: "i7j8k9l",
    platform: "android" as const,
    targetAppVersion: "1.1.x",
    message: "Security: Patch CVE-2024-1234",
    channel: "production",
    storageUri: "s3://hot-updater/0195c7bf-d48d-7785-9295-15b154d271a3.zip",
    fingerprintHash: "fp-ghi789",
    rolloutPercentage: 100,
  },
  {
    id: "0195c7be-a123-7785-9295-15b154d271a4",
    enabled: true,
    shouldForceUpdate: false,
    fileHash: "jkl012hash",
    gitCommitHash: "m0n1o2p",
    platform: "android" as const,
    targetAppVersion: "1.2.x",
    message: "Perf: Optimize image loading",
    channel: "staging",
    storageUri: "s3://hot-updater/0195c7be-a123-7785-9295-15b154d271a4.zip",
    fingerprintHash: "fp-jkl012",
    rolloutPercentage: 100,
  },
  {
    id: "0195c7bd-b234-7785-9295-15b154d271a5",
    enabled: false,
    shouldForceUpdate: false,
    fileHash: "mno345hash",
    gitCommitHash: "q3r4s5t",
    platform: "ios" as const,
    targetAppVersion: "1.3.x",
    message: "WIP: Dark mode support",
    channel: "dev",
    storageUri: "s3://hot-updater/0195c7bd-b234-7785-9295-15b154d271a5.zip",
    fingerprintHash: "fp-mno345",
    rolloutPercentage: 10,
  },
  {
    id: "0195c7bc-c345-7785-9295-15b154d271a6",
    enabled: true,
    shouldForceUpdate: false,
    fileHash: "pqr678hash",
    gitCommitHash: "u6v7w8x",
    platform: "android" as const,
    targetAppVersion: "1.2.x",
    message: "Fix: Memory leak in list view",
    channel: "dev",
    storageUri: "s3://hot-updater/0195c7bc-c345-7785-9295-15b154d271a6.zip",
    fingerprintHash: "fp-pqr678",
    rolloutPercentage: 100,
  },
];

const deviceEvents = [
  {
    id: "evt-001",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(0.5),
  },
  {
    id: "evt-002",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(1),
  },
  {
    id: "evt-003",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "RECOVERED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(1.5),
  },
  {
    id: "evt-004",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.1",
    channel: "production",
    createdAt: hoursAgo(2),
  },
  {
    id: "evt-005",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(2.5),
  },
  {
    id: "evt-006",
    deviceId: randomDeviceId(),
    bundleId: bundles[1].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(3),
  },
  {
    id: "evt-007",
    deviceId: randomDeviceId(),
    bundleId: bundles[1].id,
    eventType: "RECOVERED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(3.5),
  },
  {
    id: "evt-008",
    deviceId: randomDeviceId(),
    bundleId: bundles[1].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.1",
    channel: "production",
    createdAt: hoursAgo(4),
  },
  {
    id: "evt-009",
    deviceId: randomDeviceId(),
    bundleId: bundles[2].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.1.5",
    channel: "production",
    createdAt: hoursAgo(5),
  },
  {
    id: "evt-010",
    deviceId: randomDeviceId(),
    bundleId: bundles[2].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.1.5",
    channel: "production",
    createdAt: hoursAgo(6),
  },
  {
    id: "evt-011",
    deviceId: randomDeviceId(),
    bundleId: bundles[2].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.1.4",
    channel: "production",
    createdAt: hoursAgo(7),
  },
  {
    id: "evt-012",
    deviceId: randomDeviceId(),
    bundleId: bundles[2].id,
    eventType: "RECOVERED" as const,
    platform: "android" as const,
    appVersion: "1.1.5",
    channel: "production",
    createdAt: hoursAgo(8),
  },
  {
    id: "evt-013",
    deviceId: randomDeviceId(),
    bundleId: bundles[3].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.2.0",
    channel: "staging",
    createdAt: hoursAgo(10),
  },
  {
    id: "evt-014",
    deviceId: randomDeviceId(),
    bundleId: bundles[3].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.2.0",
    channel: "staging",
    createdAt: hoursAgo(12),
  },
  {
    id: "evt-015",
    deviceId: randomDeviceId(),
    bundleId: bundles[5].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.2.0",
    channel: "dev",
    createdAt: hoursAgo(24),
  },
  {
    id: "evt-016",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(0.1),
  },
  {
    id: "evt-017",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.1",
    channel: "production",
    createdAt: hoursAgo(0.2),
  },
  {
    id: "evt-018",
    deviceId: randomDeviceId(),
    bundleId: bundles[0].id,
    eventType: "RECOVERED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(0.3),
  },
  {
    id: "evt-019",
    deviceId: randomDeviceId(),
    bundleId: bundles[2].id,
    eventType: "PROMOTED" as const,
    platform: "android" as const,
    appVersion: "1.1.5",
    channel: "production",
    createdAt: hoursAgo(0.4),
  },
  {
    id: "evt-020",
    deviceId: randomDeviceId(),
    bundleId: bundles[1].id,
    eventType: "PROMOTED" as const,
    platform: "ios" as const,
    appVersion: "1.2.0",
    channel: "production",
    createdAt: hoursAgo(0.6),
  },
];

export default {
  projectPath: __dirname,
  updateStrategy: "fingerprint" as const,
  build: async () => null,
  storage: mockStorage({}),
  database: mockDatabase({
    latency: { min: 200, max: 400 },
    initialBundles: bundles,
    initialDeviceEvents: deviceEvents,
  }),
};
