export {
  definePlugin,
  type AnyHotUpdaterPlugin,
  type ClientAuth,
  type CoreReader,
  type HotUpdaterPlugin,
  type PluginApis,
  type PluginCli,
  type PluginClientCredential,
  type PluginClientPlugin,
  type PluginCommand,
  type PluginCommandArgument,
  type PluginCommandContext,
  type PluginCommandOption,
  type PluginCommandUi,
  type PluginContext,
  type PluginEndpoint,
  type PluginEndpointMethod,
  type PluginInstance,
  type PluginProvides,
  type PluginTableColumn,
} from "@hot-updater/plugin-core";
