export const databaseFields = {
  bundles: [
    "id",
    "platform",
    "file_hash",
    "git_commit_hash",
    "storage_uri",
    "archive_byte_size",
    "metadata",
    "manifest_storage_uri",
    "manifest_file_hash",
    "asset_base_storage_uri",
  ],
  bundle_patches: [
    "id",
    "bundle_id",
    "base_bundle_id",
    "base_file_hash",
    "patch_file_hash",
    "patch_storage_uri",
    "byte_size",
    "order_index",
  ],
  releases: [
    "id",
    "revision",
    "scope_key",
    "channel_id",
    "platform",
    "kind",
    "bundle_id",
    "strategy",
    "target_app_version",
    "fingerprint_hash",
    "enabled",
    "should_force_update",
    "message",
    "rollout_cohort_count",
    "target_cohorts",
    "operation",
    "source_release_id",
    "created_at_ms",
    "updated_at_ms",
  ],
  release_catalogs: [
    "scope_key",
    "catalog_id",
    "strategy",
    "channel_id",
    "channel_key",
    "platform",
    "fingerprint_hash",
    "generation",
    "payload",
    "catalog_hash",
    "byte_size",
    "is_tombstone",
    "updated_at_ms",
  ],
  channels: ["id", "name"],
  api_keys: [
    "id",
    "hash",
    "name",
    "prefix",
    "role",
    "created_at_ms",
    "revoked_at_ms",
  ],
} as const;
