export const databaseFields = {
  bundles: [
    "id",
    "platform",
    "should_force_update",
    "enabled",
    "file_hash",
    "git_commit_hash",
    "message",
    "channel",
    "storage_uri",
    "target_app_version",
    "fingerprint_hash",
    "metadata",
    "rollout_cohort_count",
    "target_cohorts",
    "manifest_storage_uri",
    "manifest_file_hash",
    "asset_base_storage_uri",
  ],
  bundle_patches: [
    "id",
    "bundle_id",
    "base_bundle_id",
    "base_file_hash",
    "patch_file_hash",
    "patch_storage_uri",
    "order_index",
  ],
  bundle_events: [
    "id",
    "type",
    "install_id",
    "user_id",
    "username",
    "from_bundle_id",
    "to_bundle_id",
    "platform",
    "app_version",
    "channel",
    "cohort",
    "update_strategy",
    "fingerprint_hash",
    "sdk_version",
    "received_at_ms",
  ],
} as const;
