/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigningRouteImport } from './routes/signing'
import { Route as InstallationsRouteImport } from './routes/installations'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AccessKeysRouteImport } from './routes/access-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBundlesBundleIdDownloadRouteImport } from './routes/api/bundles/$bundleId/download'

const SigningRoute = SigningRouteImport.update({
  id: '/signing',
  path: '/signing',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallationsRoute = InstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessKeysRoute = AccessKeysRouteImport.update({
  id: '/access-keys',
  path: '/access-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBundlesBundleIdDownloadRoute =
  ApiBundlesBundleIdDownloadRouteImport.update({
    id: '/api/bundles/$bundleId/download',
    path: '/api/bundles/$bundleId/download',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/installations': typeof InstallationsRoute
  '/signing': typeof SigningRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bundles/$bundleId/download': typeof ApiBundlesBundleIdDownloadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/installations': typeof InstallationsRoute
  '/signing': typeof SigningRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bundles/$bundleId/download': typeof ApiBundlesBundleIdDownloadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-keys': typeof AccessKeysRoute
  '/analytics': typeof AnalyticsRoute
  '/installations': typeof InstallationsRoute
  '/signing': typeof SigningRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bundles/$bundleId/download': typeof ApiBundlesBundleIdDownloadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/installations'
    | '/signing'
    | '/api/auth/$'
    | '/api/bundles/$bundleId/download'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/installations'
    | '/signing'
    | '/api/auth/$'
    | '/api/bundles/$bundleId/download'
  id:
    | '__root__'
    | '/'
    | '/access-keys'
    | '/analytics'
    | '/installations'
    | '/signing'
    | '/api/auth/$'
    | '/api/bundles/$bundleId/download'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessKeysRoute: typeof AccessKeysRoute
  AnalyticsRoute: typeof AnalyticsRoute
  InstallationsRoute: typeof InstallationsRoute
  SigningRoute: typeof SigningRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBundlesBundleIdDownloadRoute: typeof ApiBundlesBundleIdDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signing': {
      id: '/signing'
      path: '/signing'
      fullPath: '/signing'
      preLoaderRoute: typeof SigningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installations': {
      id: '/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof InstallationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-keys': {
      id: '/access-keys'
      path: '/access-keys'
      fullPath: '/access-keys'
      preLoaderRoute: typeof AccessKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bundles/$bundleId/download': {
      id: '/api/bundles/$bundleId/download'
      path: '/api/bundles/$bundleId/download'
      fullPath: '/api/bundles/$bundleId/download'
      preLoaderRoute: typeof ApiBundlesBundleIdDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessKeysRoute: AccessKeysRoute,
  AnalyticsRoute: AnalyticsRoute,
  InstallationsRoute: InstallationsRoute,
  SigningRoute: SigningRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBundlesBundleIdDownloadRoute: ApiBundlesBundleIdDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
