// Generated by e2e-build-config.cjs before bundling. Only public E2E settings.
export const HOT_UPDATER_APP_BASE_URL: string | undefined;
export const HOT_UPDATER_E2E_RUNTIME_CONFIG_URL: string | undefined;
export const HOT_UPDATER_API_KEY: string | undefined;
