on:
  push:
    branches:
      - main
    paths:
      - "packages/react-native/ios/**"
  pull_request:
    paths:
      - "packages/react-native/ios/**"

name: iOS Integration

jobs:
  build-new-arch:
    runs-on: macos-15
    name: Build iOS (New Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile --config.node-linker=hoisted
      - name: Install Ruby dependencies
        working-directory: examples/v0.76.1-new-arch
        run: bundle install

      - name: Library Build
        run: pnpm nx run-many --target=build --projects='@hot-updater/core,@hot-updater/react-native' --excludeTaskDependencies --parallel=false

      - name: Swift Tests
        run: pnpm test:swift

      - name: Build iOS
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd examples/v0.76.1-new-arch
          rm -f ios/Podfile.lock
          bundle exec pod install --project-directory=ios
          xcodebuild -workspace ios/HotUpdaterExample.xcworkspace -scheme HotUpdaterExample -configuration Release -sdk iphonesimulator
          cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev

  build-old-arch:
    runs-on: macos-15
    name: Build iOS (Old Architecture)
    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile --config.node-linker=hoisted
      - name: Install Ruby dependencies
        working-directory: examples/v0.74.1
        run: bundle install

      - name: Library Build
        run: pnpm nx run-many --target=build --projects='@hot-updater/core,@hot-updater/react-native' --excludeTaskDependencies --parallel=false

      - name: Swift Tests
        run: pnpm test:swift

      - name: Build iOS
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          cd examples/v0.74.1
          rm -f ios/Podfile.lock
          bundle exec pod install --project-directory=ios
          xcodebuild -workspace ios/HotUpdaterExample.xcworkspace -scheme HotUpdaterExample -configuration Release -sdk iphonesimulator
          cd ../..
        env:
          HOT_UPDATER_CHANNEL: dev
