on:
  push:
    branches:
      - main
  pull_request:

name: Integration

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - name: Setup pnpm
        uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version-file: .node-version
          cache: "pnpm"
      - name: Setup mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925
        with:
          install_args: "bun deno"
      - run: pnpm install
      - name: Build
        run: pnpm build

      - name: TypeScript type check
        run: pnpm test:type

      - name: OXC check
        run: pnpm lint
      - name: Unit test
        run: pnpm test
      - name: Integration test
        run: pnpm test:integration
